package postgres
package postgres




















































}	return err	)		`UPDATE refresh_tokens SET revoked = true WHERE user_id = $1`, userID,	_, err := r.db.ExecContext(ctx,func (r *tokenRepo) RevokeAllForUser(ctx context.Context, userID string) error {}	return err	)		`UPDATE refresh_tokens SET revoked = true WHERE token_hash = $1`, tokenHash,	_, err := r.db.ExecContext(ctx,func (r *tokenRepo) Revoke(ctx context.Context, tokenHash string) error {}	return &t, nil	}		return nil, fmt.Errorf("refresh token not found: %w", err)	if err != nil {	).Scan(&t.ID, &t.UserID, &t.TokenHash, &t.ExpiresAt, &t.Revoked, &t.CreatedAt)		 FROM refresh_tokens WHERE token_hash = $1`, tokenHash,		`SELECT id, user_id, token_hash, expires_at, revoked, created_at	err := r.db.QueryRowContext(ctx,	var t entity.RefreshTokenfunc (r *tokenRepo) GetByHash(ctx context.Context, tokenHash string) (*entity.RefreshToken, error) {}	return err	)		token.ID, token.UserID, token.TokenHash, token.ExpiresAt,		 VALUES ($1, $2, $3, $4, false, NOW())`,		`INSERT INTO refresh_tokens (id, user_id, token_hash, expires_at, revoked, created_at)	_, err := r.db.ExecContext(ctx,func (r *tokenRepo) Store(ctx context.Context, token *entity.RefreshToken) error {}	return &tokenRepo{db: db}func NewTokenRepository(db *sql.DB) repository.TokenRepository {}	db *sql.DBtype tokenRepo struct {)	"github.com/trustinbox/auth-service/internal/domain/repository"	"github.com/trustinbox/auth-service/internal/domain/entity"	"fmt"	"database/sql"	"context"import (