// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: packages/proto/organization/v1/organization.proto

package organizationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateServiceProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LegalName     string                 `protobuf:"bytes,2,opt,name=legal_name,json=legalName,proto3" json:"legal_name,omitempty"`
	Industry      string                 `protobuf:"bytes,3,opt,name=industry,proto3" json:"industry,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Website       string                 `protobuf:"bytes,5,opt,name=website,proto3" json:"website,omitempty"`
	AdminUserId   string                 `protobuf:"bytes,6,opt,name=admin_user_id,json=adminUserId,proto3" json:"admin_user_id,omitempty"`
	Address       string                 `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	City          string                 `protobuf:"bytes,8,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,9,opt,name=state,proto3" json:"state,omitempty"`
	Country       string                 `protobuf:"bytes,10,opt,name=country,proto3" json:"country,omitempty"`
	PostalCode    string                 `protobuf:"bytes,11,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Latitude      float64                `protobuf:"fixed64,12,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,13,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServiceProviderRequest) Reset() {
	*x = CreateServiceProviderRequest{}
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServiceProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceProviderRequest) ProtoMessage() {}

func (x *CreateServiceProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceProviderRequest.ProtoReflect.Descriptor instead.
func (*CreateServiceProviderRequest) Descriptor() ([]byte, []int) {
	return file_packages_proto_organization_v1_organization_proto_rawDescGZIP(), []int{0}
}

func (x *CreateServiceProviderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateServiceProviderRequest) GetLegalName() string {
	if x != nil {
		return x.LegalName
	}
	return ""
}

func (x *CreateServiceProviderRequest) GetIndustry() string {
	if x != nil {
		return x.Industry
	}
	return ""
}

func (x *CreateServiceProviderRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateServiceProviderRequest) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *CreateServiceProviderRequest) GetAdminUserId() string {
	if x != nil {
		return x.AdminUserId
	}
	return ""
}

func (x *CreateServiceProviderRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateServiceProviderRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateServiceProviderRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CreateServiceProviderRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CreateServiceProviderRequest) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *CreateServiceProviderRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CreateServiceProviderRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type GetServiceProviderRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServiceProviderId string                 `protobuf:"bytes,1,opt,name=service_provider_id,json=serviceProviderId,proto3" json:"service_provider_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetServiceProviderRequest) Reset() {
	*x = GetServiceProviderRequest{}
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceProviderRequest) ProtoMessage() {}

func (x *GetServiceProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceProviderRequest.ProtoReflect.Descriptor instead.
func (*GetServiceProviderRequest) Descriptor() ([]byte, []int) {
	return file_packages_proto_organization_v1_organization_proto_rawDescGZIP(), []int{1}
}

func (x *GetServiceProviderRequest) GetServiceProviderId() string {
	if x != nil {
		return x.ServiceProviderId
	}
	return ""
}

type ListServiceProvidersRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Search             string                 `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	VerificationStatus string                 `protobuf:"bytes,2,opt,name=verification_status,json=verificationStatus,proto3" json:"verification_status,omitempty"`
	Limit              int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset             int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ListServiceProvidersRequest) Reset() {
	*x = ListServiceProvidersRequest{}
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServiceProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServiceProvidersRequest) ProtoMessage() {}

func (x *ListServiceProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServiceProvidersRequest.ProtoReflect.Descriptor instead.
func (*ListServiceProvidersRequest) Descriptor() ([]byte, []int) {
	return file_packages_proto_organization_v1_organization_proto_rawDescGZIP(), []int{2}
}

func (x *ListServiceProvidersRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListServiceProvidersRequest) GetVerificationStatus() string {
	if x != nil {
		return x.VerificationStatus
	}
	return ""
}

func (x *ListServiceProvidersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListServiceProvidersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListServiceProvidersResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServiceProviders []*ServiceProvider     `protobuf:"bytes,1,rep,name=service_providers,json=serviceProviders,proto3" json:"service_providers,omitempty"`
	Total            int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListServiceProvidersResponse) Reset() {
	*x = ListServiceProvidersResponse{}
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServiceProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServiceProvidersResponse) ProtoMessage() {}

func (x *ListServiceProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServiceProvidersResponse.ProtoReflect.Descriptor instead.
func (*ListServiceProvidersResponse) Descriptor() ([]byte, []int) {
	return file_packages_proto_organization_v1_organization_proto_rawDescGZIP(), []int{3}
}

func (x *ListServiceProvidersResponse) GetServiceProviders() []*ServiceProvider {
	if x != nil {
		return x.ServiceProviders
	}
	return nil
}

func (x *ListServiceProvidersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateServiceProviderRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServiceProviderId string                 `protobuf:"bytes,1,opt,name=service_provider_id,json=serviceProviderId,proto3" json:"service_provider_id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LegalName         string                 `protobuf:"bytes,3,opt,name=legal_name,json=legalName,proto3" json:"legal_name,omitempty"`
	Industry          string                 `protobuf:"bytes,4,opt,name=industry,proto3" json:"industry,omitempty"`
	Description       string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Website           string                 `protobuf:"bytes,6,opt,name=website,proto3" json:"website,omitempty"`
	Address           string                 `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	City              string                 `protobuf:"bytes,8,opt,name=city,proto3" json:"city,omitempty"`
	State             string                 `protobuf:"bytes,9,opt,name=state,proto3" json:"state,omitempty"`
	Country           string                 `protobuf:"bytes,10,opt,name=country,proto3" json:"country,omitempty"`
	PostalCode        string                 `protobuf:"bytes,11,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Latitude          float64                `protobuf:"fixed64,12,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude         float64                `protobuf:"fixed64,13,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateServiceProviderRequest) Reset() {
	*x = UpdateServiceProviderRequest{}
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServiceProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceProviderRequest) ProtoMessage() {}

func (x *UpdateServiceProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceProviderRequest.ProtoReflect.Descriptor instead.
func (*UpdateServiceProviderRequest) Descriptor() ([]byte, []int) {
	return file_packages_proto_organization_v1_organization_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateServiceProviderRequest) GetServiceProviderId() string {
	if x != nil {
		return x.ServiceProviderId
	}
	return ""
}

func (x *UpdateServiceProviderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateServiceProviderRequest) GetLegalName() string {
	if x != nil {
		return x.LegalName
	}
	return ""
}

func (x *UpdateServiceProviderRequest) GetIndustry() string {
	if x != nil {
		return x.Industry
	}
	return ""
}

func (x *UpdateServiceProviderRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateServiceProviderRequest) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *UpdateServiceProviderRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpdateServiceProviderRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UpdateServiceProviderRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *UpdateServiceProviderRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *UpdateServiceProviderRequest) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *UpdateServiceProviderRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *UpdateServiceProviderRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type ServiceProvider struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LegalName          string                 `protobuf:"bytes,3,opt,name=legal_name,json=legalName,proto3" json:"legal_name,omitempty"`
	Industry           string                 `protobuf:"bytes,4,opt,name=industry,proto3" json:"industry,omitempty"`
	Description        string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	VerificationStatus string                 `protobuf:"bytes,6,opt,name=verification_status,json=verificationStatus,proto3" json:"verification_status,omitempty"` // PENDING, VERIFIED, REJECTED, SUSPENDED
	Status             string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`                                                   // ACTIVE, SUSPENDED, DEACTIVATED
	Website            string                 `protobuf:"bytes,8,opt,name=website,proto3" json:"website,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Address            string                 `protobuf:"bytes,11,opt,name=address,proto3" json:"address,omitempty"`
	City               string                 `protobuf:"bytes,12,opt,name=city,proto3" json:"city,omitempty"`
	State              string                 `protobuf:"bytes,13,opt,name=state,proto3" json:"state,omitempty"`
	Country            string                 `protobuf:"bytes,14,opt,name=country,proto3" json:"country,omitempty"`
	PostalCode         string                 `protobuf:"bytes,15,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Latitude           float64                `protobuf:"fixed64,16,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude          float64                `protobuf:"fixed64,17,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ServiceProvider) Reset() {
	*x = ServiceProvider{}
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceProvider) ProtoMessage() {}

func (x *ServiceProvider) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceProvider.ProtoReflect.Descriptor instead.
func (*ServiceProvider) Descriptor() ([]byte, []int) {
	return file_packages_proto_organization_v1_organization_proto_rawDescGZIP(), []int{5}
}

func (x *ServiceProvider) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServiceProvider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceProvider) GetLegalName() string {
	if x != nil {
		return x.LegalName
	}
	return ""
}

func (x *ServiceProvider) GetIndustry() string {
	if x != nil {
		return x.Industry
	}
	return ""
}

func (x *ServiceProvider) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ServiceProvider) GetVerificationStatus() string {
	if x != nil {
		return x.VerificationStatus
	}
	return ""
}

func (x *ServiceProvider) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ServiceProvider) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *ServiceProvider) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ServiceProvider) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ServiceProvider) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ServiceProvider) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ServiceProvider) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ServiceProvider) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *ServiceProvider) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *ServiceProvider) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *ServiceProvider) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type VerifyServiceProviderRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServiceProviderId string                 `protobuf:"bytes,1,opt,name=service_provider_id,json=serviceProviderId,proto3" json:"service_provider_id,omitempty"`
	Decision          string                 `protobuf:"bytes,2,opt,name=decision,proto3" json:"decision,omitempty"` // APPROVED, REJECTED
	Reason            string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	AdminUserId       string                 `protobuf:"bytes,4,opt,name=admin_user_id,json=adminUserId,proto3" json:"admin_user_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VerifyServiceProviderRequest) Reset() {
	*x = VerifyServiceProviderRequest{}
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyServiceProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyServiceProviderRequest) ProtoMessage() {}

func (x *VerifyServiceProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyServiceProviderRequest.ProtoReflect.Descriptor instead.
func (*VerifyServiceProviderRequest) Descriptor() ([]byte, []int) {
	return file_packages_proto_organization_v1_organization_proto_rawDescGZIP(), []int{6}
}

func (x *VerifyServiceProviderRequest) GetServiceProviderId() string {
	if x != nil {
		return x.ServiceProviderId
	}
	return ""
}

func (x *VerifyServiceProviderRequest) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *VerifyServiceProviderRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *VerifyServiceProviderRequest) GetAdminUserId() string {
	if x != nil {
		return x.AdminUserId
	}
	return ""
}

type VerifyServiceProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyServiceProviderResponse) Reset() {
	*x = VerifyServiceProviderResponse{}
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyServiceProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyServiceProviderResponse) ProtoMessage() {}

func (x *VerifyServiceProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyServiceProviderResponse.ProtoReflect.Descriptor instead.
func (*VerifyServiceProviderResponse) Descriptor() ([]byte, []int) {
	return file_packages_proto_organization_v1_organization_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyServiceProviderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SuspendServiceProviderRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServiceProviderId string                 `protobuf:"bytes,1,opt,name=service_provider_id,json=serviceProviderId,proto3" json:"service_provider_id,omitempty"`
	Reason            string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	AdminUserId       string                 `protobuf:"bytes,3,opt,name=admin_user_id,json=adminUserId,proto3" json:"admin_user_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SuspendServiceProviderRequest) Reset() {
	*x = SuspendServiceProviderRequest{}
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendServiceProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendServiceProviderRequest) ProtoMessage() {}

func (x *SuspendServiceProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendServiceProviderRequest.ProtoReflect.Descriptor instead.
func (*SuspendServiceProviderRequest) Descriptor() ([]byte, []int) {
	return file_packages_proto_organization_v1_organization_proto_rawDescGZIP(), []int{8}
}

func (x *SuspendServiceProviderRequest) GetServiceProviderId() string {
	if x != nil {
		return x.ServiceProviderId
	}
	return ""
}

func (x *SuspendServiceProviderRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SuspendServiceProviderRequest) GetAdminUserId() string {
	if x != nil {
		return x.AdminUserId
	}
	return ""
}

type SuspendServiceProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendServiceProviderResponse) Reset() {
	*x = SuspendServiceProviderResponse{}
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendServiceProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendServiceProviderResponse) ProtoMessage() {}

func (x *SuspendServiceProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendServiceProviderResponse.ProtoReflect.Descriptor instead.
func (*SuspendServiceProviderResponse) Descriptor() ([]byte, []int) {
	return file_packages_proto_organization_v1_organization_proto_rawDescGZIP(), []int{9}
}

func (x *SuspendServiceProviderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AddServiceProviderUserRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServiceProviderId string                 `protobuf:"bytes,1,opt,name=service_provider_id,json=serviceProviderId,proto3" json:"service_provider_id,omitempty"`
	UserId            string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role              string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"` // SP_ADMIN, AGENT, ANALYST
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AddServiceProviderUserRequest) Reset() {
	*x = AddServiceProviderUserRequest{}
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddServiceProviderUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddServiceProviderUserRequest) ProtoMessage() {}

func (x *AddServiceProviderUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddServiceProviderUserRequest.ProtoReflect.Descriptor instead.
func (*AddServiceProviderUserRequest) Descriptor() ([]byte, []int) {
	return file_packages_proto_organization_v1_organization_proto_rawDescGZIP(), []int{10}
}

func (x *AddServiceProviderUserRequest) GetServiceProviderId() string {
	if x != nil {
		return x.ServiceProviderId
	}
	return ""
}

func (x *AddServiceProviderUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddServiceProviderUserRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type ServiceProviderUser struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServiceProviderId string                 `protobuf:"bytes,2,opt,name=service_provider_id,json=serviceProviderId,proto3" json:"service_provider_id,omitempty"`
	UserId            string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role              string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Status            string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ServiceProviderUser) Reset() {
	*x = ServiceProviderUser{}
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceProviderUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceProviderUser) ProtoMessage() {}

func (x *ServiceProviderUser) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceProviderUser.ProtoReflect.Descriptor instead.
func (*ServiceProviderUser) Descriptor() ([]byte, []int) {
	return file_packages_proto_organization_v1_organization_proto_rawDescGZIP(), []int{11}
}

func (x *ServiceProviderUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServiceProviderUser) GetServiceProviderId() string {
	if x != nil {
		return x.ServiceProviderId
	}
	return ""
}

func (x *ServiceProviderUser) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ServiceProviderUser) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ServiceProviderUser) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ServiceProviderUser) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type RemoveServiceProviderUserRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ServiceProviderUserId string                 `protobuf:"bytes,1,opt,name=service_provider_user_id,json=serviceProviderUserId,proto3" json:"service_provider_user_id,omitempty"`
	ServiceProviderId     string                 `protobuf:"bytes,2,opt,name=service_provider_id,json=serviceProviderId,proto3" json:"service_provider_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RemoveServiceProviderUserRequest) Reset() {
	*x = RemoveServiceProviderUserRequest{}
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveServiceProviderUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveServiceProviderUserRequest) ProtoMessage() {}

func (x *RemoveServiceProviderUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveServiceProviderUserRequest.ProtoReflect.Descriptor instead.
func (*RemoveServiceProviderUserRequest) Descriptor() ([]byte, []int) {
	return file_packages_proto_organization_v1_organization_proto_rawDescGZIP(), []int{12}
}

func (x *RemoveServiceProviderUserRequest) GetServiceProviderUserId() string {
	if x != nil {
		return x.ServiceProviderUserId
	}
	return ""
}

func (x *RemoveServiceProviderUserRequest) GetServiceProviderId() string {
	if x != nil {
		return x.ServiceProviderId
	}
	return ""
}

type RemoveServiceProviderUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveServiceProviderUserResponse) Reset() {
	*x = RemoveServiceProviderUserResponse{}
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveServiceProviderUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveServiceProviderUserResponse) ProtoMessage() {}

func (x *RemoveServiceProviderUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveServiceProviderUserResponse.ProtoReflect.Descriptor instead.
func (*RemoveServiceProviderUserResponse) Descriptor() ([]byte, []int) {
	return file_packages_proto_organization_v1_organization_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveServiceProviderUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListServiceProviderUsersRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServiceProviderId string                 `protobuf:"bytes,1,opt,name=service_provider_id,json=serviceProviderId,proto3" json:"service_provider_id,omitempty"`
	Limit             int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset            int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListServiceProviderUsersRequest) Reset() {
	*x = ListServiceProviderUsersRequest{}
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServiceProviderUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServiceProviderUsersRequest) ProtoMessage() {}

func (x *ListServiceProviderUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServiceProviderUsersRequest.ProtoReflect.Descriptor instead.
func (*ListServiceProviderUsersRequest) Descriptor() ([]byte, []int) {
	return file_packages_proto_organization_v1_organization_proto_rawDescGZIP(), []int{14}
}

func (x *ListServiceProviderUsersRequest) GetServiceProviderId() string {
	if x != nil {
		return x.ServiceProviderId
	}
	return ""
}

func (x *ListServiceProviderUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListServiceProviderUsersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListServiceProviderUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*ServiceProviderUser `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServiceProviderUsersResponse) Reset() {
	*x = ListServiceProviderUsersResponse{}
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServiceProviderUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServiceProviderUsersResponse) ProtoMessage() {}

func (x *ListServiceProviderUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServiceProviderUsersResponse.ProtoReflect.Descriptor instead.
func (*ListServiceProviderUsersResponse) Descriptor() ([]byte, []int) {
	return file_packages_proto_organization_v1_organization_proto_rawDescGZIP(), []int{15}
}

func (x *ListServiceProviderUsersResponse) GetUsers() []*ServiceProviderUser {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListServiceProviderUsersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetServiceProviderUserRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ServiceProviderUserId string                 `protobuf:"bytes,1,opt,name=service_provider_user_id,json=serviceProviderUserId,proto3" json:"service_provider_user_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetServiceProviderUserRequest) Reset() {
	*x = GetServiceProviderUserRequest{}
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceProviderUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceProviderUserRequest) ProtoMessage() {}

func (x *GetServiceProviderUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceProviderUserRequest.ProtoReflect.Descriptor instead.
func (*GetServiceProviderUserRequest) Descriptor() ([]byte, []int) {
	return file_packages_proto_organization_v1_organization_proto_rawDescGZIP(), []int{16}
}

func (x *GetServiceProviderUserRequest) GetServiceProviderUserId() string {
	if x != nil {
		return x.ServiceProviderUserId
	}
	return ""
}

type InviteTeamMemberRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServiceProviderId string                 `protobuf:"bytes,1,opt,name=service_provider_id,json=serviceProviderId,proto3" json:"service_provider_id,omitempty"`
	Email             string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Role              string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"` // SP_ADMIN, AGENT, ANALYST
	InvitedByUserId   string                 `protobuf:"bytes,4,opt,name=invited_by_user_id,json=invitedByUserId,proto3" json:"invited_by_user_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InviteTeamMemberRequest) Reset() {
	*x = InviteTeamMemberRequest{}
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteTeamMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteTeamMemberRequest) ProtoMessage() {}

func (x *InviteTeamMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteTeamMemberRequest.ProtoReflect.Descriptor instead.
func (*InviteTeamMemberRequest) Descriptor() ([]byte, []int) {
	return file_packages_proto_organization_v1_organization_proto_rawDescGZIP(), []int{17}
}

func (x *InviteTeamMemberRequest) GetServiceProviderId() string {
	if x != nil {
		return x.ServiceProviderId
	}
	return ""
}

func (x *InviteTeamMemberRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *InviteTeamMemberRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *InviteTeamMemberRequest) GetInvitedByUserId() string {
	if x != nil {
		return x.InvitedByUserId
	}
	return ""
}

type InviteTeamMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvitationId  string                 `protobuf:"bytes,1,opt,name=invitation_id,json=invitationId,proto3" json:"invitation_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteTeamMemberResponse) Reset() {
	*x = InviteTeamMemberResponse{}
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteTeamMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteTeamMemberResponse) ProtoMessage() {}

func (x *InviteTeamMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteTeamMemberResponse.ProtoReflect.Descriptor instead.
func (*InviteTeamMemberResponse) Descriptor() ([]byte, []int) {
	return file_packages_proto_organization_v1_organization_proto_rawDescGZIP(), []int{18}
}

func (x *InviteTeamMemberResponse) GetInvitationId() string {
	if x != nil {
		return x.InvitationId
	}
	return ""
}

func (x *InviteTeamMemberResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AcceptInvitationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptInvitationRequest) Reset() {
	*x = AcceptInvitationRequest{}
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptInvitationRequest) ProtoMessage() {}

func (x *AcceptInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptInvitationRequest.ProtoReflect.Descriptor instead.
func (*AcceptInvitationRequest) Descriptor() ([]byte, []int) {
	return file_packages_proto_organization_v1_organization_proto_rawDescGZIP(), []int{19}
}

func (x *AcceptInvitationRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AcceptInvitationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AcceptInvitationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptInvitationResponse) Reset() {
	*x = AcceptInvitationResponse{}
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptInvitationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptInvitationResponse) ProtoMessage() {}

func (x *AcceptInvitationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptInvitationResponse.ProtoReflect.Descriptor instead.
func (*AcceptInvitationResponse) Descriptor() ([]byte, []int) {
	return file_packages_proto_organization_v1_organization_proto_rawDescGZIP(), []int{20}
}

func (x *AcceptInvitationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RevokeInvitationRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	InvitationId      string                 `protobuf:"bytes,1,opt,name=invitation_id,json=invitationId,proto3" json:"invitation_id,omitempty"`
	ServiceProviderId string                 `protobuf:"bytes,2,opt,name=service_provider_id,json=serviceProviderId,proto3" json:"service_provider_id,omitempty"`
	ActorUserId       string                 `protobuf:"bytes,3,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RevokeInvitationRequest) Reset() {
	*x = RevokeInvitationRequest{}
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeInvitationRequest) ProtoMessage() {}

func (x *RevokeInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeInvitationRequest.ProtoReflect.Descriptor instead.
func (*RevokeInvitationRequest) Descriptor() ([]byte, []int) {
	return file_packages_proto_organization_v1_organization_proto_rawDescGZIP(), []int{21}
}

func (x *RevokeInvitationRequest) GetInvitationId() string {
	if x != nil {
		return x.InvitationId
	}
	return ""
}

func (x *RevokeInvitationRequest) GetServiceProviderId() string {
	if x != nil {
		return x.ServiceProviderId
	}
	return ""
}

func (x *RevokeInvitationRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

type RevokeInvitationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeInvitationResponse) Reset() {
	*x = RevokeInvitationResponse{}
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeInvitationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeInvitationResponse) ProtoMessage() {}

func (x *RevokeInvitationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeInvitationResponse.ProtoReflect.Descriptor instead.
func (*RevokeInvitationResponse) Descriptor() ([]byte, []int) {
	return file_packages_proto_organization_v1_organization_proto_rawDescGZIP(), []int{22}
}

func (x *RevokeInvitationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListInvitationsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServiceProviderId string                 `protobuf:"bytes,1,opt,name=service_provider_id,json=serviceProviderId,proto3" json:"service_provider_id,omitempty"`
	Status            string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // PENDING, ACCEPTED, EXPIRED, REVOKED (empty = all)
	Limit             int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset            int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListInvitationsRequest) Reset() {
	*x = ListInvitationsRequest{}
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvitationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvitationsRequest) ProtoMessage() {}

func (x *ListInvitationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvitationsRequest.ProtoReflect.Descriptor instead.
func (*ListInvitationsRequest) Descriptor() ([]byte, []int) {
	return file_packages_proto_organization_v1_organization_proto_rawDescGZIP(), []int{23}
}

func (x *ListInvitationsRequest) GetServiceProviderId() string {
	if x != nil {
		return x.ServiceProviderId
	}
	return ""
}

func (x *ListInvitationsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListInvitationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListInvitationsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListInvitationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invitations   []*Invitation          `protobuf:"bytes,1,rep,name=invitations,proto3" json:"invitations,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvitationsResponse) Reset() {
	*x = ListInvitationsResponse{}
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvitationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvitationsResponse) ProtoMessage() {}

func (x *ListInvitationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvitationsResponse.ProtoReflect.Descriptor instead.
func (*ListInvitationsResponse) Descriptor() ([]byte, []int) {
	return file_packages_proto_organization_v1_organization_proto_rawDescGZIP(), []int{24}
}

func (x *ListInvitationsResponse) GetInvitations() []*Invitation {
	if x != nil {
		return x.Invitations
	}
	return nil
}

func (x *ListInvitationsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Invitation struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email             string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	ServiceProviderId string                 `protobuf:"bytes,3,opt,name=service_provider_id,json=serviceProviderId,proto3" json:"service_provider_id,omitempty"`
	Role              string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Status            string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	InvitedBy         string                 `protobuf:"bytes,6,opt,name=invited_by,json=invitedBy,proto3" json:"invited_by,omitempty"`
	ExpiresAt         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Invitation) Reset() {
	*x = Invitation{}
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invitation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invitation) ProtoMessage() {}

func (x *Invitation) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invitation.ProtoReflect.Descriptor instead.
func (*Invitation) Descriptor() ([]byte, []int) {
	return file_packages_proto_organization_v1_organization_proto_rawDescGZIP(), []int{25}
}

func (x *Invitation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Invitation) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Invitation) GetServiceProviderId() string {
	if x != nil {
		return x.ServiceProviderId
	}
	return ""
}

func (x *Invitation) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Invitation) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Invitation) GetInvitedBy() string {
	if x != nil {
		return x.InvitedBy
	}
	return ""
}

func (x *Invitation) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Invitation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ChangeTeamMemberRoleRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServiceProviderId string                 `protobuf:"bytes,1,opt,name=service_provider_id,json=serviceProviderId,proto3" json:"service_provider_id,omitempty"`
	TargetUserId      string                 `protobuf:"bytes,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	NewRole           string                 `protobuf:"bytes,3,opt,name=new_role,json=newRole,proto3" json:"new_role,omitempty"` // SP_ADMIN, AGENT, ANALYST
	ActorUserId       string                 `protobuf:"bytes,4,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ChangeTeamMemberRoleRequest) Reset() {
	*x = ChangeTeamMemberRoleRequest{}
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeTeamMemberRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeTeamMemberRoleRequest) ProtoMessage() {}

func (x *ChangeTeamMemberRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeTeamMemberRoleRequest.ProtoReflect.Descriptor instead.
func (*ChangeTeamMemberRoleRequest) Descriptor() ([]byte, []int) {
	return file_packages_proto_organization_v1_organization_proto_rawDescGZIP(), []int{26}
}

func (x *ChangeTeamMemberRoleRequest) GetServiceProviderId() string {
	if x != nil {
		return x.ServiceProviderId
	}
	return ""
}

func (x *ChangeTeamMemberRoleRequest) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *ChangeTeamMemberRoleRequest) GetNewRole() string {
	if x != nil {
		return x.NewRole
	}
	return ""
}

func (x *ChangeTeamMemberRoleRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

type ChangeTeamMemberRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeTeamMemberRoleResponse) Reset() {
	*x = ChangeTeamMemberRoleResponse{}
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeTeamMemberRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeTeamMemberRoleResponse) ProtoMessage() {}

func (x *ChangeTeamMemberRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeTeamMemberRoleResponse.ProtoReflect.Descriptor instead.
func (*ChangeTeamMemberRoleResponse) Descriptor() ([]byte, []int) {
	return file_packages_proto_organization_v1_organization_proto_rawDescGZIP(), []int{27}
}

func (x *ChangeTeamMemberRoleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RemoveTeamMemberRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServiceProviderId string                 `protobuf:"bytes,1,opt,name=service_provider_id,json=serviceProviderId,proto3" json:"service_provider_id,omitempty"`
	TargetUserId      string                 `protobuf:"bytes,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	ActorUserId       string                 `protobuf:"bytes,3,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RemoveTeamMemberRequest) Reset() {
	*x = RemoveTeamMemberRequest{}
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTeamMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTeamMemberRequest) ProtoMessage() {}

func (x *RemoveTeamMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTeamMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveTeamMemberRequest) Descriptor() ([]byte, []int) {
	return file_packages_proto_organization_v1_organization_proto_rawDescGZIP(), []int{28}
}

func (x *RemoveTeamMemberRequest) GetServiceProviderId() string {
	if x != nil {
		return x.ServiceProviderId
	}
	return ""
}

func (x *RemoveTeamMemberRequest) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *RemoveTeamMemberRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

type RemoveTeamMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTeamMemberResponse) Reset() {
	*x = RemoveTeamMemberResponse{}
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTeamMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTeamMemberResponse) ProtoMessage() {}

func (x *RemoveTeamMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_organization_v1_organization_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTeamMemberResponse.ProtoReflect.Descriptor instead.
func (*RemoveTeamMemberResponse) Descriptor() ([]byte, []int) {
	return file_packages_proto_organization_v1_organization_proto_rawDescGZIP(), []int{29}
}

func (x *RemoveTeamMemberResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_packages_proto_organization_v1_organization_proto protoreflect.FileDescriptor

const file_packages_proto_organization_v1_organization_proto_rawDesc = "" +
	"\n" +
	"1packages/proto/organization/v1/organization.proto\x12\x0forganization.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x86\x03\n" +
	"\x1cCreateServiceProviderRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"legal_name\x18\x02 \x01(\tR\tlegalName\x12\x1a\n" +
	"\bindustry\x18\x03 \x01(\tR\bindustry\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x18\n" +
	"\awebsite\x18\x05 \x01(\tR\awebsite\x12\"\n" +
	"\radmin_user_id\x18\x06 \x01(\tR\vadminUserId\x12\x18\n" +
	"\aaddress\x18\a \x01(\tR\aaddress\x12\x12\n" +
	"\x04city\x18\b \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\t \x01(\tR\x05state\x12\x18\n" +
	"\acountry\x18\n" +
	" \x01(\tR\acountry\x12\x1f\n" +
	"\vpostal_code\x18\v \x01(\tR\n" +
	"postalCode\x12\x1a\n" +
	"\blatitude\x18\f \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\r \x01(\x01R\tlongitude\"K\n" +
	"\x19GetServiceProviderRequest\x12.\n" +
	"\x13service_provider_id\x18\x01 \x01(\tR\x11serviceProviderId\"\x94\x01\n" +
	"\x1bListServiceProvidersRequest\x12\x16\n" +
	"\x06search\x18\x01 \x01(\tR\x06search\x12/\n" +
	"\x13verification_status\x18\x02 \x01(\tR\x12verificationStatus\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"\x83\x01\n" +
	"\x1cListServiceProvidersResponse\x12M\n" +
	"\x11service_providers\x18\x01 \x03(\v2 .organization.v1.ServiceProviderR\x10serviceProviders\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x92\x03\n" +
	"\x1cUpdateServiceProviderRequest\x12.\n" +
	"\x13service_provider_id\x18\x01 \x01(\tR\x11serviceProviderId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"legal_name\x18\x03 \x01(\tR\tlegalName\x12\x1a\n" +
	"\bindustry\x18\x04 \x01(\tR\bindustry\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x18\n" +
	"\awebsite\x18\x06 \x01(\tR\awebsite\x12\x18\n" +
	"\aaddress\x18\a \x01(\tR\aaddress\x12\x12\n" +
	"\x04city\x18\b \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\t \x01(\tR\x05state\x12\x18\n" +
	"\acountry\x18\n" +
	" \x01(\tR\acountry\x12\x1f\n" +
	"\vpostal_code\x18\v \x01(\tR\n" +
	"postalCode\x12\x1a\n" +
	"\blatitude\x18\f \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\r \x01(\x01R\tlongitude\"\xa4\x04\n" +
	"\x0fServiceProvider\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"legal_name\x18\x03 \x01(\tR\tlegalName\x12\x1a\n" +
	"\bindustry\x18\x04 \x01(\tR\bindustry\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12/\n" +
	"\x13verification_status\x18\x06 \x01(\tR\x12verificationStatus\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x18\n" +
	"\awebsite\x18\b \x01(\tR\awebsite\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x18\n" +
	"\aaddress\x18\v \x01(\tR\aaddress\x12\x12\n" +
	"\x04city\x18\f \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\r \x01(\tR\x05state\x12\x18\n" +
	"\acountry\x18\x0e \x01(\tR\acountry\x12\x1f\n" +
	"\vpostal_code\x18\x0f \x01(\tR\n" +
	"postalCode\x12\x1a\n" +
	"\blatitude\x18\x10 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x11 \x01(\x01R\tlongitude\"\xa6\x01\n" +
	"\x1cVerifyServiceProviderRequest\x12.\n" +
	"\x13service_provider_id\x18\x01 \x01(\tR\x11serviceProviderId\x12\x1a\n" +
	"\bdecision\x18\x02 \x01(\tR\bdecision\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\"\n" +
	"\radmin_user_id\x18\x04 \x01(\tR\vadminUserId\"9\n" +
	"\x1dVerifyServiceProviderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x8b\x01\n" +
	"\x1dSuspendServiceProviderRequest\x12.\n" +
	"\x13service_provider_id\x18\x01 \x01(\tR\x11serviceProviderId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\"\n" +
	"\radmin_user_id\x18\x03 \x01(\tR\vadminUserId\":\n" +
	"\x1eSuspendServiceProviderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"|\n" +
	"\x1dAddServiceProviderUserRequest\x12.\n" +
	"\x13service_provider_id\x18\x01 \x01(\tR\x11serviceProviderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"\xd5\x01\n" +
	"\x13ServiceProviderUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x13service_provider_id\x18\x02 \x01(\tR\x11serviceProviderId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x8b\x01\n" +
	" RemoveServiceProviderUserRequest\x127\n" +
	"\x18service_provider_user_id\x18\x01 \x01(\tR\x15serviceProviderUserId\x12.\n" +
	"\x13service_provider_id\x18\x02 \x01(\tR\x11serviceProviderId\"=\n" +
	"!RemoveServiceProviderUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x7f\n" +
	"\x1fListServiceProviderUsersRequest\x12.\n" +
	"\x13service_provider_id\x18\x01 \x01(\tR\x11serviceProviderId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"t\n" +
	" ListServiceProviderUsersResponse\x12:\n" +
	"\x05users\x18\x01 \x03(\v2$.organization.v1.ServiceProviderUserR\x05users\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"X\n" +
	"\x1dGetServiceProviderUserRequest\x127\n" +
	"\x18service_provider_user_id\x18\x01 \x01(\tR\x15serviceProviderUserId\"\xa0\x01\n" +
	"\x17InviteTeamMemberRequest\x12.\n" +
	"\x13service_provider_id\x18\x01 \x01(\tR\x11serviceProviderId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12+\n" +
	"\x12invited_by_user_id\x18\x04 \x01(\tR\x0finvitedByUserId\"U\n" +
	"\x18InviteTeamMemberResponse\x12#\n" +
	"\rinvitation_id\x18\x01 \x01(\tR\finvitationId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"H\n" +
	"\x17AcceptInvitationRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"4\n" +
	"\x18AcceptInvitationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x92\x01\n" +
	"\x17RevokeInvitationRequest\x12#\n" +
	"\rinvitation_id\x18\x01 \x01(\tR\finvitationId\x12.\n" +
	"\x13service_provider_id\x18\x02 \x01(\tR\x11serviceProviderId\x12\"\n" +
	"\ractor_user_id\x18\x03 \x01(\tR\vactorUserId\"4\n" +
	"\x18RevokeInvitationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x8e\x01\n" +
	"\x16ListInvitationsRequest\x12.\n" +
	"\x13service_provider_id\x18\x01 \x01(\tR\x11serviceProviderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"n\n" +
	"\x17ListInvitationsResponse\x12=\n" +
	"\vinvitations\x18\x01 \x03(\v2\x1b.organization.v1.InvitationR\vinvitations\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xa3\x02\n" +
	"\n" +
	"Invitation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12.\n" +
	"\x13service_provider_id\x18\x03 \x01(\tR\x11serviceProviderId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"invited_by\x18\x06 \x01(\tR\tinvitedBy\x129\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xb2\x01\n" +
	"\x1bChangeTeamMemberRoleRequest\x12.\n" +
	"\x13service_provider_id\x18\x01 \x01(\tR\x11serviceProviderId\x12$\n" +
	"\x0etarget_user_id\x18\x02 \x01(\tR\ftargetUserId\x12\x19\n" +
	"\bnew_role\x18\x03 \x01(\tR\anewRole\x12\"\n" +
	"\ractor_user_id\x18\x04 \x01(\tR\vactorUserId\"8\n" +
	"\x1cChangeTeamMemberRoleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x93\x01\n" +
	"\x17RemoveTeamMemberRequest\x12.\n" +
	"\x13service_provider_id\x18\x01 \x01(\tR\x11serviceProviderId\x12$\n" +
	"\x0etarget_user_id\x18\x02 \x01(\tR\ftargetUserId\x12\"\n" +
	"\ractor_user_id\x18\x03 \x01(\tR\vactorUserId\"4\n" +
	"\x18RemoveTeamMemberResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x9d\x0e\n" +
	"\x16ServiceProviderService\x12h\n" +
	"\x15CreateServiceProvider\x12-.organization.v1.CreateServiceProviderRequest\x1a .organization.v1.ServiceProvider\x12b\n" +
	"\x12GetServiceProvider\x12*.organization.v1.GetServiceProviderRequest\x1a .organization.v1.ServiceProvider\x12s\n" +
	"\x14ListServiceProviders\x12,.organization.v1.ListServiceProvidersRequest\x1a-.organization.v1.ListServiceProvidersResponse\x12h\n" +
	"\x15UpdateServiceProvider\x12-.organization.v1.UpdateServiceProviderRequest\x1a .organization.v1.ServiceProvider\x12v\n" +
	"\x15VerifyServiceProvider\x12-.organization.v1.VerifyServiceProviderRequest\x1a..organization.v1.VerifyServiceProviderResponse\x12y\n" +
	"\x16SuspendServiceProvider\x12..organization.v1.SuspendServiceProviderRequest\x1a/.organization.v1.SuspendServiceProviderResponse\x12n\n" +
	"\x16AddServiceProviderUser\x12..organization.v1.AddServiceProviderUserRequest\x1a$.organization.v1.ServiceProviderUser\x12\x82\x01\n" +
	"\x19RemoveServiceProviderUser\x121.organization.v1.RemoveServiceProviderUserRequest\x1a2.organization.v1.RemoveServiceProviderUserResponse\x12\x7f\n" +
	"\x18ListServiceProviderUsers\x120.organization.v1.ListServiceProviderUsersRequest\x1a1.organization.v1.ListServiceProviderUsersResponse\x12n\n" +
	"\x16GetServiceProviderUser\x12..organization.v1.GetServiceProviderUserRequest\x1a$.organization.v1.ServiceProviderUser\x12g\n" +
	"\x10InviteTeamMember\x12(.organization.v1.InviteTeamMemberRequest\x1a).organization.v1.InviteTeamMemberResponse\x12g\n" +
	"\x10AcceptInvitation\x12(.organization.v1.AcceptInvitationRequest\x1a).organization.v1.AcceptInvitationResponse\x12g\n" +
	"\x10RevokeInvitation\x12(.organization.v1.RevokeInvitationRequest\x1a).organization.v1.RevokeInvitationResponse\x12d\n" +
	"\x0fListInvitations\x12'.organization.v1.ListInvitationsRequest\x1a(.organization.v1.ListInvitationsResponse\x12s\n" +
	"\x14ChangeTeamMemberRole\x12,.organization.v1.ChangeTeamMemberRoleRequest\x1a-.organization.v1.ChangeTeamMemberRoleResponse\x12g\n" +
	"\x10RemoveTeamMember\x12(.organization.v1.RemoveTeamMemberRequest\x1a).organization.v1.RemoveTeamMemberResponseB@Z>github.com/trustinbox/proto/gen/organization/v1;organizationv1b\x06proto3"

var (
	file_packages_proto_organization_v1_organization_proto_rawDescOnce sync.Once
	file_packages_proto_organization_v1_organization_proto_rawDescData []byte
)

func file_packages_proto_organization_v1_organization_proto_rawDescGZIP() []byte {
	file_packages_proto_organization_v1_organization_proto_rawDescOnce.Do(func() {
		file_packages_proto_organization_v1_organization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packages_proto_organization_v1_organization_proto_rawDesc), len(file_packages_proto_organization_v1_organization_proto_rawDesc)))
	})
	return file_packages_proto_organization_v1_organization_proto_rawDescData
}

var file_packages_proto_organization_v1_organization_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_packages_proto_organization_v1_organization_proto_goTypes = []any{
	(*CreateServiceProviderRequest)(nil),      // 0: organization.v1.CreateServiceProviderRequest
	(*GetServiceProviderRequest)(nil),         // 1: organization.v1.GetServiceProviderRequest
	(*ListServiceProvidersRequest)(nil),       // 2: organization.v1.ListServiceProvidersRequest
	(*ListServiceProvidersResponse)(nil),      // 3: organization.v1.ListServiceProvidersResponse
	(*UpdateServiceProviderRequest)(nil),      // 4: organization.v1.UpdateServiceProviderRequest
	(*ServiceProvider)(nil),                   // 5: organization.v1.ServiceProvider
	(*VerifyServiceProviderRequest)(nil),      // 6: organization.v1.VerifyServiceProviderRequest
	(*VerifyServiceProviderResponse)(nil),     // 7: organization.v1.VerifyServiceProviderResponse
	(*SuspendServiceProviderRequest)(nil),     // 8: organization.v1.SuspendServiceProviderRequest
	(*SuspendServiceProviderResponse)(nil),    // 9: organization.v1.SuspendServiceProviderResponse
	(*AddServiceProviderUserRequest)(nil),     // 10: organization.v1.AddServiceProviderUserRequest
	(*ServiceProviderUser)(nil),               // 11: organization.v1.ServiceProviderUser
	(*RemoveServiceProviderUserRequest)(nil),  // 12: organization.v1.RemoveServiceProviderUserRequest
	(*RemoveServiceProviderUserResponse)(nil), // 13: organization.v1.RemoveServiceProviderUserResponse
	(*ListServiceProviderUsersRequest)(nil),   // 14: organization.v1.ListServiceProviderUsersRequest
	(*ListServiceProviderUsersResponse)(nil),  // 15: organization.v1.ListServiceProviderUsersResponse
	(*GetServiceProviderUserRequest)(nil),     // 16: organization.v1.GetServiceProviderUserRequest
	(*InviteTeamMemberRequest)(nil),           // 17: organization.v1.InviteTeamMemberRequest
	(*InviteTeamMemberResponse)(nil),          // 18: organization.v1.InviteTeamMemberResponse
	(*AcceptInvitationRequest)(nil),           // 19: organization.v1.AcceptInvitationRequest
	(*AcceptInvitationResponse)(nil),          // 20: organization.v1.AcceptInvitationResponse
	(*RevokeInvitationRequest)(nil),           // 21: organization.v1.RevokeInvitationRequest
	(*RevokeInvitationResponse)(nil),          // 22: organization.v1.RevokeInvitationResponse
	(*ListInvitationsRequest)(nil),            // 23: organization.v1.ListInvitationsRequest
	(*ListInvitationsResponse)(nil),           // 24: organization.v1.ListInvitationsResponse
	(*Invitation)(nil),                        // 25: organization.v1.Invitation
	(*ChangeTeamMemberRoleRequest)(nil),       // 26: organization.v1.ChangeTeamMemberRoleRequest
	(*ChangeTeamMemberRoleResponse)(nil),      // 27: organization.v1.ChangeTeamMemberRoleResponse
	(*RemoveTeamMemberRequest)(nil),           // 28: organization.v1.RemoveTeamMemberRequest
	(*RemoveTeamMemberResponse)(nil),          // 29: organization.v1.RemoveTeamMemberResponse
	(*timestamppb.Timestamp)(nil),             // 30: google.protobuf.Timestamp
}
var file_packages_proto_organization_v1_organization_proto_depIdxs = []int32{
	5,  // 0: organization.v1.ListServiceProvidersResponse.service_providers:type_name -> organization.v1.ServiceProvider
	30, // 1: organization.v1.ServiceProvider.created_at:type_name -> google.protobuf.Timestamp
	30, // 2: organization.v1.ServiceProvider.updated_at:type_name -> google.protobuf.Timestamp
	30, // 3: organization.v1.ServiceProviderUser.created_at:type_name -> google.protobuf.Timestamp
	11, // 4: organization.v1.ListServiceProviderUsersResponse.users:type_name -> organization.v1.ServiceProviderUser
	25, // 5: organization.v1.ListInvitationsResponse.invitations:type_name -> organization.v1.Invitation
	30, // 6: organization.v1.Invitation.expires_at:type_name -> google.protobuf.Timestamp
	30, // 7: organization.v1.Invitation.created_at:type_name -> google.protobuf.Timestamp
	0,  // 8: organization.v1.ServiceProviderService.CreateServiceProvider:input_type -> organization.v1.CreateServiceProviderRequest
	1,  // 9: organization.v1.ServiceProviderService.GetServiceProvider:input_type -> organization.v1.GetServiceProviderRequest
	2,  // 10: organization.v1.ServiceProviderService.ListServiceProviders:input_type -> organization.v1.ListServiceProvidersRequest
	4,  // 11: organization.v1.ServiceProviderService.UpdateServiceProvider:input_type -> organization.v1.UpdateServiceProviderRequest
	6,  // 12: organization.v1.ServiceProviderService.VerifyServiceProvider:input_type -> organization.v1.VerifyServiceProviderRequest
	8,  // 13: organization.v1.ServiceProviderService.SuspendServiceProvider:input_type -> organization.v1.SuspendServiceProviderRequest
	10, // 14: organization.v1.ServiceProviderService.AddServiceProviderUser:input_type -> organization.v1.AddServiceProviderUserRequest
	12, // 15: organization.v1.ServiceProviderService.RemoveServiceProviderUser:input_type -> organization.v1.RemoveServiceProviderUserRequest
	14, // 16: organization.v1.ServiceProviderService.ListServiceProviderUsers:input_type -> organization.v1.ListServiceProviderUsersRequest
	16, // 17: organization.v1.ServiceProviderService.GetServiceProviderUser:input_type -> organization.v1.GetServiceProviderUserRequest
	17, // 18: organization.v1.ServiceProviderService.InviteTeamMember:input_type -> organization.v1.InviteTeamMemberRequest
	19, // 19: organization.v1.ServiceProviderService.AcceptInvitation:input_type -> organization.v1.AcceptInvitationRequest
	21, // 20: organization.v1.ServiceProviderService.RevokeInvitation:input_type -> organization.v1.RevokeInvitationRequest
	23, // 21: organization.v1.ServiceProviderService.ListInvitations:input_type -> organization.v1.ListInvitationsRequest
	26, // 22: organization.v1.ServiceProviderService.ChangeTeamMemberRole:input_type -> organization.v1.ChangeTeamMemberRoleRequest
	28, // 23: organization.v1.ServiceProviderService.RemoveTeamMember:input_type -> organization.v1.RemoveTeamMemberRequest
	5,  // 24: organization.v1.ServiceProviderService.CreateServiceProvider:output_type -> organization.v1.ServiceProvider
	5,  // 25: organization.v1.ServiceProviderService.GetServiceProvider:output_type -> organization.v1.ServiceProvider
	3,  // 26: organization.v1.ServiceProviderService.ListServiceProviders:output_type -> organization.v1.ListServiceProvidersResponse
	5,  // 27: organization.v1.ServiceProviderService.UpdateServiceProvider:output_type -> organization.v1.ServiceProvider
	7,  // 28: organization.v1.ServiceProviderService.VerifyServiceProvider:output_type -> organization.v1.VerifyServiceProviderResponse
	9,  // 29: organization.v1.ServiceProviderService.SuspendServiceProvider:output_type -> organization.v1.SuspendServiceProviderResponse
	11, // 30: organization.v1.ServiceProviderService.AddServiceProviderUser:output_type -> organization.v1.ServiceProviderUser
	13, // 31: organization.v1.ServiceProviderService.RemoveServiceProviderUser:output_type -> organization.v1.RemoveServiceProviderUserResponse
	15, // 32: organization.v1.ServiceProviderService.ListServiceProviderUsers:output_type -> organization.v1.ListServiceProviderUsersResponse
	11, // 33: organization.v1.ServiceProviderService.GetServiceProviderUser:output_type -> organization.v1.ServiceProviderUser
	18, // 34: organization.v1.ServiceProviderService.InviteTeamMember:output_type -> organization.v1.InviteTeamMemberResponse
	20, // 35: organization.v1.ServiceProviderService.AcceptInvitation:output_type -> organization.v1.AcceptInvitationResponse
	22, // 36: organization.v1.ServiceProviderService.RevokeInvitation:output_type -> organization.v1.RevokeInvitationResponse
	24, // 37: organization.v1.ServiceProviderService.ListInvitations:output_type -> organization.v1.ListInvitationsResponse
	27, // 38: organization.v1.ServiceProviderService.ChangeTeamMemberRole:output_type -> organization.v1.ChangeTeamMemberRoleResponse
	29, // 39: organization.v1.ServiceProviderService.RemoveTeamMember:output_type -> organization.v1.RemoveTeamMemberResponse
	24, // [24:40] is the sub-list for method output_type
	8,  // [8:24] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_packages_proto_organization_v1_organization_proto_init() }
func file_packages_proto_organization_v1_organization_proto_init() {
	if File_packages_proto_organization_v1_organization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packages_proto_organization_v1_organization_proto_rawDesc), len(file_packages_proto_organization_v1_organization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_packages_proto_organization_v1_organization_proto_goTypes,
		DependencyIndexes: file_packages_proto_organization_v1_organization_proto_depIdxs,
		MessageInfos:      file_packages_proto_organization_v1_organization_proto_msgTypes,
	}.Build()
	File_packages_proto_organization_v1_organization_proto = out.File
	file_packages_proto_organization_v1_organization_proto_goTypes = nil
	file_packages_proto_organization_v1_organization_proto_depIdxs = nil
}
