export const SEGMENT_LABELS: Record<string, string> = {
  customers: 'Customers',
  notifications: 'Notifications',
  compose: 'Compose',
  conversations: 'Conversations',
  callbacks: 'Callbacks',
  documents: 'Documents',
  campaigns: 'Campaigns',
  new: 'New',
  knowledge: 'Knowledge Base',
  analytics: 'Analytics',
  webhooks: 'Webhooks',
  compliance: 'Compliance',
  integrations: 'Integrations',
  settings: 'Settings',
  profile: 'Profile',
  team: 'Team',
  industry: 'Industry',
  cms: 'Content',
  editor: 'Editor',
  media: 'Media Library',
  roles: 'CMS Roles',
  auth: 'Auth',
  login: 'Login',
  register: 'Register',
  invite: 'Invite',
};
