// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: packages/proto/user/v1/user.proto

package userv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserService_GetUserProfile_FullMethodName              = "/user.v1.UserService/GetUserProfile"
	UserService_UpdateUserProfile_FullMethodName           = "/user.v1.UserService/UpdateUserProfile"
	UserService_GetPrivacyPreference_FullMethodName        = "/user.v1.UserService/GetPrivacyPreference"
	UserService_UpdatePrivacyPreference_FullMethodName     = "/user.v1.UserService/UpdatePrivacyPreference"
	UserService_ListAvailabilitySlots_FullMethodName       = "/user.v1.UserService/ListAvailabilitySlots"
	UserService_CreateAvailabilitySlot_FullMethodName      = "/user.v1.UserService/CreateAvailabilitySlot"
	UserService_DeleteAvailabilitySlot_FullMethodName      = "/user.v1.UserService/DeleteAvailabilitySlot"
	UserService_ListDNDRules_FullMethodName                = "/user.v1.UserService/ListDNDRules"
	UserService_CreateDNDRule_FullMethodName               = "/user.v1.UserService/CreateDNDRule"
	UserService_UpdateDNDRule_FullMethodName               = "/user.v1.UserService/UpdateDNDRule"
	UserService_DeleteDNDRule_FullMethodName               = "/user.v1.UserService/DeleteDNDRule"
	UserService_BlockServiceProvider_FullMethodName        = "/user.v1.UserService/BlockServiceProvider"
	UserService_UnblockServiceProvider_FullMethodName      = "/user.v1.UserService/UnblockServiceProvider"
	UserService_ListBlockedServiceProviders_FullMethodName = "/user.v1.UserService/ListBlockedServiceProviders"
	UserService_CreateAddress_FullMethodName               = "/user.v1.UserService/CreateAddress"
	UserService_UpdateAddress_FullMethodName               = "/user.v1.UserService/UpdateAddress"
	UserService_DeleteAddress_FullMethodName               = "/user.v1.UserService/DeleteAddress"
	UserService_ListAddresses_FullMethodName               = "/user.v1.UserService/ListAddresses"
	UserService_SetCurrentAddress_FullMethodName           = "/user.v1.UserService/SetCurrentAddress"
	UserService_GetCurrentAddress_FullMethodName           = "/user.v1.UserService/GetCurrentAddress"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	GetUserProfile(ctx context.Context, in *GetUserProfileRequest, opts ...grpc.CallOption) (*GetUserProfileResponse, error)
	UpdateUserProfile(ctx context.Context, in *UpdateUserProfileRequest, opts ...grpc.CallOption) (*UpdateUserProfileResponse, error)
	GetPrivacyPreference(ctx context.Context, in *GetPrivacyPreferenceRequest, opts ...grpc.CallOption) (*PrivacyPreference, error)
	UpdatePrivacyPreference(ctx context.Context, in *UpdatePrivacyPreferenceRequest, opts ...grpc.CallOption) (*PrivacyPreference, error)
	ListAvailabilitySlots(ctx context.Context, in *ListAvailabilitySlotsRequest, opts ...grpc.CallOption) (*ListAvailabilitySlotsResponse, error)
	CreateAvailabilitySlot(ctx context.Context, in *CreateAvailabilitySlotRequest, opts ...grpc.CallOption) (*AvailabilitySlot, error)
	DeleteAvailabilitySlot(ctx context.Context, in *DeleteAvailabilitySlotRequest, opts ...grpc.CallOption) (*DeleteAvailabilitySlotResponse, error)
	ListDNDRules(ctx context.Context, in *ListDNDRulesRequest, opts ...grpc.CallOption) (*ListDNDRulesResponse, error)
	CreateDNDRule(ctx context.Context, in *CreateDNDRuleRequest, opts ...grpc.CallOption) (*DNDRule, error)
	UpdateDNDRule(ctx context.Context, in *UpdateDNDRuleRequest, opts ...grpc.CallOption) (*DNDRule, error)
	DeleteDNDRule(ctx context.Context, in *DeleteDNDRuleRequest, opts ...grpc.CallOption) (*DeleteDNDRuleResponse, error)
	BlockServiceProvider(ctx context.Context, in *BlockServiceProviderRequest, opts ...grpc.CallOption) (*BlockServiceProviderResponse, error)
	UnblockServiceProvider(ctx context.Context, in *UnblockServiceProviderRequest, opts ...grpc.CallOption) (*UnblockServiceProviderResponse, error)
	ListBlockedServiceProviders(ctx context.Context, in *ListBlockedServiceProvidersRequest, opts ...grpc.CallOption) (*ListBlockedServiceProvidersResponse, error)
	// Addresses
	CreateAddress(ctx context.Context, in *CreateAddressRequest, opts ...grpc.CallOption) (*UserAddress, error)
	UpdateAddress(ctx context.Context, in *UpdateAddressRequest, opts ...grpc.CallOption) (*UserAddress, error)
	DeleteAddress(ctx context.Context, in *DeleteAddressRequest, opts ...grpc.CallOption) (*DeleteAddressResponse, error)
	ListAddresses(ctx context.Context, in *ListAddressesRequest, opts ...grpc.CallOption) (*ListAddressesResponse, error)
	SetCurrentAddress(ctx context.Context, in *SetCurrentAddressRequest, opts ...grpc.CallOption) (*SetCurrentAddressResponse, error)
	GetCurrentAddress(ctx context.Context, in *GetCurrentAddressRequest, opts ...grpc.CallOption) (*UserAddress, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetUserProfile(ctx context.Context, in *GetUserProfileRequest, opts ...grpc.CallOption) (*GetUserProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserProfileResponse)
	err := c.cc.Invoke(ctx, UserService_GetUserProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUserProfile(ctx context.Context, in *UpdateUserProfileRequest, opts ...grpc.CallOption) (*UpdateUserProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserProfileResponse)
	err := c.cc.Invoke(ctx, UserService_UpdateUserProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetPrivacyPreference(ctx context.Context, in *GetPrivacyPreferenceRequest, opts ...grpc.CallOption) (*PrivacyPreference, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrivacyPreference)
	err := c.cc.Invoke(ctx, UserService_GetPrivacyPreference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdatePrivacyPreference(ctx context.Context, in *UpdatePrivacyPreferenceRequest, opts ...grpc.CallOption) (*PrivacyPreference, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrivacyPreference)
	err := c.cc.Invoke(ctx, UserService_UpdatePrivacyPreference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListAvailabilitySlots(ctx context.Context, in *ListAvailabilitySlotsRequest, opts ...grpc.CallOption) (*ListAvailabilitySlotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAvailabilitySlotsResponse)
	err := c.cc.Invoke(ctx, UserService_ListAvailabilitySlots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateAvailabilitySlot(ctx context.Context, in *CreateAvailabilitySlotRequest, opts ...grpc.CallOption) (*AvailabilitySlot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AvailabilitySlot)
	err := c.cc.Invoke(ctx, UserService_CreateAvailabilitySlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteAvailabilitySlot(ctx context.Context, in *DeleteAvailabilitySlotRequest, opts ...grpc.CallOption) (*DeleteAvailabilitySlotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAvailabilitySlotResponse)
	err := c.cc.Invoke(ctx, UserService_DeleteAvailabilitySlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListDNDRules(ctx context.Context, in *ListDNDRulesRequest, opts ...grpc.CallOption) (*ListDNDRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDNDRulesResponse)
	err := c.cc.Invoke(ctx, UserService_ListDNDRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateDNDRule(ctx context.Context, in *CreateDNDRuleRequest, opts ...grpc.CallOption) (*DNDRule, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DNDRule)
	err := c.cc.Invoke(ctx, UserService_CreateDNDRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateDNDRule(ctx context.Context, in *UpdateDNDRuleRequest, opts ...grpc.CallOption) (*DNDRule, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DNDRule)
	err := c.cc.Invoke(ctx, UserService_UpdateDNDRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteDNDRule(ctx context.Context, in *DeleteDNDRuleRequest, opts ...grpc.CallOption) (*DeleteDNDRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDNDRuleResponse)
	err := c.cc.Invoke(ctx, UserService_DeleteDNDRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) BlockServiceProvider(ctx context.Context, in *BlockServiceProviderRequest, opts ...grpc.CallOption) (*BlockServiceProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlockServiceProviderResponse)
	err := c.cc.Invoke(ctx, UserService_BlockServiceProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UnblockServiceProvider(ctx context.Context, in *UnblockServiceProviderRequest, opts ...grpc.CallOption) (*UnblockServiceProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnblockServiceProviderResponse)
	err := c.cc.Invoke(ctx, UserService_UnblockServiceProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListBlockedServiceProviders(ctx context.Context, in *ListBlockedServiceProvidersRequest, opts ...grpc.CallOption) (*ListBlockedServiceProvidersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBlockedServiceProvidersResponse)
	err := c.cc.Invoke(ctx, UserService_ListBlockedServiceProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateAddress(ctx context.Context, in *CreateAddressRequest, opts ...grpc.CallOption) (*UserAddress, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserAddress)
	err := c.cc.Invoke(ctx, UserService_CreateAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateAddress(ctx context.Context, in *UpdateAddressRequest, opts ...grpc.CallOption) (*UserAddress, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserAddress)
	err := c.cc.Invoke(ctx, UserService_UpdateAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteAddress(ctx context.Context, in *DeleteAddressRequest, opts ...grpc.CallOption) (*DeleteAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAddressResponse)
	err := c.cc.Invoke(ctx, UserService_DeleteAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListAddresses(ctx context.Context, in *ListAddressesRequest, opts ...grpc.CallOption) (*ListAddressesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAddressesResponse)
	err := c.cc.Invoke(ctx, UserService_ListAddresses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SetCurrentAddress(ctx context.Context, in *SetCurrentAddressRequest, opts ...grpc.CallOption) (*SetCurrentAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetCurrentAddressResponse)
	err := c.cc.Invoke(ctx, UserService_SetCurrentAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetCurrentAddress(ctx context.Context, in *GetCurrentAddressRequest, opts ...grpc.CallOption) (*UserAddress, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserAddress)
	err := c.cc.Invoke(ctx, UserService_GetCurrentAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
type UserServiceServer interface {
	GetUserProfile(context.Context, *GetUserProfileRequest) (*GetUserProfileResponse, error)
	UpdateUserProfile(context.Context, *UpdateUserProfileRequest) (*UpdateUserProfileResponse, error)
	GetPrivacyPreference(context.Context, *GetPrivacyPreferenceRequest) (*PrivacyPreference, error)
	UpdatePrivacyPreference(context.Context, *UpdatePrivacyPreferenceRequest) (*PrivacyPreference, error)
	ListAvailabilitySlots(context.Context, *ListAvailabilitySlotsRequest) (*ListAvailabilitySlotsResponse, error)
	CreateAvailabilitySlot(context.Context, *CreateAvailabilitySlotRequest) (*AvailabilitySlot, error)
	DeleteAvailabilitySlot(context.Context, *DeleteAvailabilitySlotRequest) (*DeleteAvailabilitySlotResponse, error)
	ListDNDRules(context.Context, *ListDNDRulesRequest) (*ListDNDRulesResponse, error)
	CreateDNDRule(context.Context, *CreateDNDRuleRequest) (*DNDRule, error)
	UpdateDNDRule(context.Context, *UpdateDNDRuleRequest) (*DNDRule, error)
	DeleteDNDRule(context.Context, *DeleteDNDRuleRequest) (*DeleteDNDRuleResponse, error)
	BlockServiceProvider(context.Context, *BlockServiceProviderRequest) (*BlockServiceProviderResponse, error)
	UnblockServiceProvider(context.Context, *UnblockServiceProviderRequest) (*UnblockServiceProviderResponse, error)
	ListBlockedServiceProviders(context.Context, *ListBlockedServiceProvidersRequest) (*ListBlockedServiceProvidersResponse, error)
	// Addresses
	CreateAddress(context.Context, *CreateAddressRequest) (*UserAddress, error)
	UpdateAddress(context.Context, *UpdateAddressRequest) (*UserAddress, error)
	DeleteAddress(context.Context, *DeleteAddressRequest) (*DeleteAddressResponse, error)
	ListAddresses(context.Context, *ListAddressesRequest) (*ListAddressesResponse, error)
	SetCurrentAddress(context.Context, *SetCurrentAddressRequest) (*SetCurrentAddressResponse, error)
	GetCurrentAddress(context.Context, *GetCurrentAddressRequest) (*UserAddress, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) GetUserProfile(context.Context, *GetUserProfileRequest) (*GetUserProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserProfile not implemented")
}
func (UnimplementedUserServiceServer) UpdateUserProfile(context.Context, *UpdateUserProfileRequest) (*UpdateUserProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserProfile not implemented")
}
func (UnimplementedUserServiceServer) GetPrivacyPreference(context.Context, *GetPrivacyPreferenceRequest) (*PrivacyPreference, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPrivacyPreference not implemented")
}
func (UnimplementedUserServiceServer) UpdatePrivacyPreference(context.Context, *UpdatePrivacyPreferenceRequest) (*PrivacyPreference, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePrivacyPreference not implemented")
}
func (UnimplementedUserServiceServer) ListAvailabilitySlots(context.Context, *ListAvailabilitySlotsRequest) (*ListAvailabilitySlotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAvailabilitySlots not implemented")
}
func (UnimplementedUserServiceServer) CreateAvailabilitySlot(context.Context, *CreateAvailabilitySlotRequest) (*AvailabilitySlot, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAvailabilitySlot not implemented")
}
func (UnimplementedUserServiceServer) DeleteAvailabilitySlot(context.Context, *DeleteAvailabilitySlotRequest) (*DeleteAvailabilitySlotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAvailabilitySlot not implemented")
}
func (UnimplementedUserServiceServer) ListDNDRules(context.Context, *ListDNDRulesRequest) (*ListDNDRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDNDRules not implemented")
}
func (UnimplementedUserServiceServer) CreateDNDRule(context.Context, *CreateDNDRuleRequest) (*DNDRule, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDNDRule not implemented")
}
func (UnimplementedUserServiceServer) UpdateDNDRule(context.Context, *UpdateDNDRuleRequest) (*DNDRule, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDNDRule not implemented")
}
func (UnimplementedUserServiceServer) DeleteDNDRule(context.Context, *DeleteDNDRuleRequest) (*DeleteDNDRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDNDRule not implemented")
}
func (UnimplementedUserServiceServer) BlockServiceProvider(context.Context, *BlockServiceProviderRequest) (*BlockServiceProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BlockServiceProvider not implemented")
}
func (UnimplementedUserServiceServer) UnblockServiceProvider(context.Context, *UnblockServiceProviderRequest) (*UnblockServiceProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnblockServiceProvider not implemented")
}
func (UnimplementedUserServiceServer) ListBlockedServiceProviders(context.Context, *ListBlockedServiceProvidersRequest) (*ListBlockedServiceProvidersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBlockedServiceProviders not implemented")
}
func (UnimplementedUserServiceServer) CreateAddress(context.Context, *CreateAddressRequest) (*UserAddress, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAddress not implemented")
}
func (UnimplementedUserServiceServer) UpdateAddress(context.Context, *UpdateAddressRequest) (*UserAddress, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAddress not implemented")
}
func (UnimplementedUserServiceServer) DeleteAddress(context.Context, *DeleteAddressRequest) (*DeleteAddressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAddress not implemented")
}
func (UnimplementedUserServiceServer) ListAddresses(context.Context, *ListAddressesRequest) (*ListAddressesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAddresses not implemented")
}
func (UnimplementedUserServiceServer) SetCurrentAddress(context.Context, *SetCurrentAddressRequest) (*SetCurrentAddressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetCurrentAddress not implemented")
}
func (UnimplementedUserServiceServer) GetCurrentAddress(context.Context, *GetCurrentAddressRequest) (*UserAddress, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentAddress not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call panics, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_GetUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUserProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserProfile(ctx, req.(*GetUserProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateUserProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUserProfile(ctx, req.(*UpdateUserProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetPrivacyPreference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPrivacyPreferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetPrivacyPreference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetPrivacyPreference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetPrivacyPreference(ctx, req.(*GetPrivacyPreferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdatePrivacyPreference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePrivacyPreferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdatePrivacyPreference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdatePrivacyPreference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdatePrivacyPreference(ctx, req.(*UpdatePrivacyPreferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListAvailabilitySlots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAvailabilitySlotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListAvailabilitySlots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ListAvailabilitySlots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListAvailabilitySlots(ctx, req.(*ListAvailabilitySlotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateAvailabilitySlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAvailabilitySlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateAvailabilitySlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CreateAvailabilitySlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateAvailabilitySlot(ctx, req.(*CreateAvailabilitySlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteAvailabilitySlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAvailabilitySlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteAvailabilitySlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_DeleteAvailabilitySlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteAvailabilitySlot(ctx, req.(*DeleteAvailabilitySlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListDNDRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDNDRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListDNDRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ListDNDRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListDNDRules(ctx, req.(*ListDNDRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateDNDRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDNDRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateDNDRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CreateDNDRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateDNDRule(ctx, req.(*CreateDNDRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateDNDRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDNDRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateDNDRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateDNDRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateDNDRule(ctx, req.(*UpdateDNDRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteDNDRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDNDRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteDNDRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_DeleteDNDRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteDNDRule(ctx, req.(*DeleteDNDRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_BlockServiceProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockServiceProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).BlockServiceProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_BlockServiceProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).BlockServiceProvider(ctx, req.(*BlockServiceProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UnblockServiceProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnblockServiceProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UnblockServiceProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UnblockServiceProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UnblockServiceProvider(ctx, req.(*UnblockServiceProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListBlockedServiceProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBlockedServiceProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListBlockedServiceProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ListBlockedServiceProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListBlockedServiceProviders(ctx, req.(*ListBlockedServiceProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CreateAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateAddress(ctx, req.(*CreateAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateAddress(ctx, req.(*UpdateAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_DeleteAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteAddress(ctx, req.(*DeleteAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAddressesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ListAddresses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListAddresses(ctx, req.(*ListAddressesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SetCurrentAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCurrentAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SetCurrentAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_SetCurrentAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SetCurrentAddress(ctx, req.(*SetCurrentAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetCurrentAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetCurrentAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetCurrentAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetCurrentAddress(ctx, req.(*GetCurrentAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.v1.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserProfile",
			Handler:    _UserService_GetUserProfile_Handler,
		},
		{
			MethodName: "UpdateUserProfile",
			Handler:    _UserService_UpdateUserProfile_Handler,
		},
		{
			MethodName: "GetPrivacyPreference",
			Handler:    _UserService_GetPrivacyPreference_Handler,
		},
		{
			MethodName: "UpdatePrivacyPreference",
			Handler:    _UserService_UpdatePrivacyPreference_Handler,
		},
		{
			MethodName: "ListAvailabilitySlots",
			Handler:    _UserService_ListAvailabilitySlots_Handler,
		},
		{
			MethodName: "CreateAvailabilitySlot",
			Handler:    _UserService_CreateAvailabilitySlot_Handler,
		},
		{
			MethodName: "DeleteAvailabilitySlot",
			Handler:    _UserService_DeleteAvailabilitySlot_Handler,
		},
		{
			MethodName: "ListDNDRules",
			Handler:    _UserService_ListDNDRules_Handler,
		},
		{
			MethodName: "CreateDNDRule",
			Handler:    _UserService_CreateDNDRule_Handler,
		},
		{
			MethodName: "UpdateDNDRule",
			Handler:    _UserService_UpdateDNDRule_Handler,
		},
		{
			MethodName: "DeleteDNDRule",
			Handler:    _UserService_DeleteDNDRule_Handler,
		},
		{
			MethodName: "BlockServiceProvider",
			Handler:    _UserService_BlockServiceProvider_Handler,
		},
		{
			MethodName: "UnblockServiceProvider",
			Handler:    _UserService_UnblockServiceProvider_Handler,
		},
		{
			MethodName: "ListBlockedServiceProviders",
			Handler:    _UserService_ListBlockedServiceProviders_Handler,
		},
		{
			MethodName: "CreateAddress",
			Handler:    _UserService_CreateAddress_Handler,
		},
		{
			MethodName: "UpdateAddress",
			Handler:    _UserService_UpdateAddress_Handler,
		},
		{
			MethodName: "DeleteAddress",
			Handler:    _UserService_DeleteAddress_Handler,
		},
		{
			MethodName: "ListAddresses",
			Handler:    _UserService_ListAddresses_Handler,
		},
		{
			MethodName: "SetCurrentAddress",
			Handler:    _UserService_SetCurrentAddress_Handler,
		},
		{
			MethodName: "GetCurrentAddress",
			Handler:    _UserService_GetCurrentAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "packages/proto/user/v1/user.proto",
}
