package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"database/sql"
	"fmt"
	"time"

	"github.com/trustinbox/cornerstone/auth/requestctx"
	"github.com/trustinbox/graphql-bff/graph/generated"
	"github.com/trustinbox/graphql-bff/graph/model"
	commpb "github.com/trustinbox/proto/gen/communication/v1"
	notifpb "github.com/trustinbox/proto/gen/notification/v1"
	orgpb "github.com/trustinbox/proto/gen/organization/v1"
	userpb "github.com/trustinbox/proto/gen/user/v1"
	"go.uber.org/zap"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// UpdatePrivacyPreference is the resolver for the updatePrivacyPreference field.
func (r *mutationResolver) UpdatePrivacyPreference(ctx context.Context, input model.UpdatePrivacyPreferenceInput) (*model.PrivacyPreference, error) {
	userID := requestctx.UserID(ctx)
	if userID == "" {
		return nil, fmt.Errorf("authentication required")
	}

	req := &userpb.UpdatePrivacyPreferenceRequest{UserId: userID}
	if input.AllowPersonalNotifications != nil {
		req.AllowPersonalNotifications = input.AllowPersonalNotifications
	}
	if input.AllowSPNotifications != nil {
		req.AllowSpNotifications = input.AllowSPNotifications
	}
	if input.AllowAdvertisements != nil {
		req.AllowAdvertisements = input.AllowAdvertisements
	}
	if input.AllowCallbackRequests != nil {
		req.AllowCallbackRequests = input.AllowCallbackRequests
	}
	if input.AllowChat != nil {
		req.AllowChat = input.AllowChat
	}
	if input.AllowDocumentShares != nil {
		req.AllowDocumentShares = input.AllowDocumentShares
	}
	if input.RequireCallApproval != nil {
		req.RequireCallApproval = input.RequireCallApproval
	}
	if input.NotificationSoundEnabled != nil {
		req.NotificationSoundEnabled = input.NotificationSoundEnabled
	}

	resp, err := r.Clients.User.UpdatePrivacyPreference(ctx, req)
	if err != nil {
		r.Log.Error("failed to update privacy preference", zap.Error(err), zap.String("user_id", userID))
		return nil, fmt.Errorf("failed to update privacy preference: %w", err)
	}
	return mapPrivacyPreferenceFromProto(resp), nil
}

// CreateDNDRule is the resolver for the createDNDRule field.
func (r *mutationResolver) CreateDNDRule(ctx context.Context, input model.CreateDNDRuleInput) (*model.DNDRule, error) {
	userID := requestctx.UserID(ctx)
	if userID == "" {
		return nil, fmt.Errorf("authentication required")
	}

	daysOfWeek := make([]int32, len(input.DaysOfWeek))
	for i, d := range input.DaysOfWeek {
		daysOfWeek[i] = int32(d)
	}

	resp, err := r.Clients.User.CreateDNDRule(ctx, &userpb.CreateDNDRuleRequest{
		UserId:     userID,
		ScopeType:  input.ScopeType,
		ScopeRefId: strOrEmpty(input.ScopeRefID),
		StartTime:  input.StartTime,
		EndTime:    input.EndTime,
		DaysOfWeek: daysOfWeek,
		IsActive:   input.IsActive,
	})
	if err != nil {
		r.Log.Error("failed to create DND rule", zap.Error(err), zap.String("user_id", userID))
		return nil, fmt.Errorf("failed to create DND rule: %w", err)
	}
	return mapDNDRuleFromProto(resp), nil
}

// UpdateDNDRule is the resolver for the updateDNDRule field.
func (r *mutationResolver) UpdateDNDRule(ctx context.Context, input model.UpdateDNDRuleInput) (*model.DNDRule, error) {
	userID := requestctx.UserID(ctx)
	if userID == "" {
		return nil, fmt.Errorf("authentication required")
	}

	req := &userpb.UpdateDNDRuleRequest{
		Id:     input.ID,
		UserId: userID,
	}
	if input.StartTime != nil {
		req.StartTime = *input.StartTime
	}
	if input.EndTime != nil {
		req.EndTime = *input.EndTime
	}
	if input.DaysOfWeek != nil {
		days := make([]int32, len(input.DaysOfWeek))
		for i, d := range input.DaysOfWeek {
			days[i] = int32(d)
		}
		req.DaysOfWeek = days
	}
	if input.IsActive != nil {
		req.IsActive = *input.IsActive
	}

	resp, err := r.Clients.User.UpdateDNDRule(ctx, req)
	if err != nil {
		r.Log.Error("failed to update DND rule", zap.Error(err), zap.String("user_id", userID))
		return nil, fmt.Errorf("failed to update DND rule: %w", err)
	}
	return mapDNDRuleFromProto(resp), nil
}

// DeleteDNDRule is the resolver for the deleteDNDRule field.
func (r *mutationResolver) DeleteDNDRule(ctx context.Context, id string) (bool, error) {
	userID := requestctx.UserID(ctx)
	if userID == "" {
		return false, fmt.Errorf("authentication required")
	}

	resp, err := r.Clients.User.DeleteDNDRule(ctx, &userpb.DeleteDNDRuleRequest{
		Id:     id,
		UserId: userID,
	})
	if err != nil {
		r.Log.Error("failed to delete DND rule", zap.Error(err), zap.String("user_id", userID))
		return false, fmt.Errorf("failed to delete DND rule: %w", err)
	}
	return resp.Success, nil
}

// CreateAvailabilitySlot is the resolver for the createAvailabilitySlot field.
func (r *mutationResolver) CreateAvailabilitySlot(ctx context.Context, input model.CreateAvailabilitySlotInput) (*model.AvailabilitySlot, error) {
	userID := requestctx.UserID(ctx)
	if userID == "" {
		return nil, fmt.Errorf("authentication required")
	}

	resp, err := r.Clients.User.CreateAvailabilitySlot(ctx, &userpb.CreateAvailabilitySlotRequest{
		UserId:    userID,
		DayOfWeek: int32(input.DayOfWeek),
		StartTime: input.StartTime,
		EndTime:   input.EndTime,
		SlotType:  input.SlotType,
	})
	if err != nil {
		r.Log.Error("failed to create availability slot", zap.Error(err), zap.String("user_id", userID))
		return nil, fmt.Errorf("failed to create availability slot: %w", err)
	}
	return mapAvailabilitySlotFromProto(resp), nil
}

// DeleteAvailabilitySlot is the resolver for the deleteAvailabilitySlot field.
func (r *mutationResolver) DeleteAvailabilitySlot(ctx context.Context, id string) (bool, error) {
	userID := requestctx.UserID(ctx)
	if userID == "" {
		return false, fmt.Errorf("authentication required")
	}

	resp, err := r.Clients.User.DeleteAvailabilitySlot(ctx, &userpb.DeleteAvailabilitySlotRequest{
		Id:     id,
		UserId: userID,
	})
	if err != nil {
		r.Log.Error("failed to delete availability slot", zap.Error(err), zap.String("user_id", userID))
		return false, fmt.Errorf("failed to delete availability slot: %w", err)
	}
	return resp.Success, nil
}

// ApproveCallbackRequest is the resolver for the approveCallbackRequest field.
func (r *mutationResolver) ApproveCallbackRequest(ctx context.Context, input model.ApproveCallbackRequestInput) (*model.CallbackRequest, error) {
	userID := requestctx.UserID(ctx)
	if userID == "" {
		return nil, fmt.Errorf("authentication required")
	}

	_, err := r.Clients.Communication.ApproveCallbackRequest(ctx, &commpb.ApproveCallbackRequestRequest{
		CallbackRequestId: input.CallbackRequestID,
		UserId:            userID,
		ApprovedSlotStart: timestamppb.New(input.ApprovedSlotStart),
		ApprovedSlotEnd:   timestamppb.New(input.ApprovedSlotEnd),
	})
	if err != nil {
		r.Log.Error("failed to approve callback request", zap.Error(err), zap.String("user_id", userID))
		return nil, fmt.Errorf("failed to approve callback request: %w", err)
	}

	cb, err := r.Clients.Communication.GetCallbackRequest(ctx, &commpb.GetCallbackRequestRequest{
		CallbackRequestId: input.CallbackRequestID,
		UserId:            userID,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to fetch updated callback request: %w", err)
	}
	return mapCallbackRequestFromProto(cb), nil
}

// RejectCallbackRequest is the resolver for the rejectCallbackRequest field.
func (r *mutationResolver) RejectCallbackRequest(ctx context.Context, input model.RejectCallbackRequestInput) (*model.CallbackRequest, error) {
	userID := requestctx.UserID(ctx)
	if userID == "" {
		return nil, fmt.Errorf("authentication required")
	}

	reason := ""
	if input.Reason != nil {
		reason = *input.Reason
	}

	_, err := r.Clients.Communication.RejectCallbackRequest(ctx, &commpb.RejectCallbackRequestRequest{
		CallbackRequestId: input.CallbackRequestID,
		UserId:            userID,
		Reason:            reason,
	})
	if err != nil {
		r.Log.Error("failed to reject callback request", zap.Error(err), zap.String("user_id", userID))
		return nil, fmt.Errorf("failed to reject callback request: %w", err)
	}

	cb, err := r.Clients.Communication.GetCallbackRequest(ctx, &commpb.GetCallbackRequestRequest{
		CallbackRequestId: input.CallbackRequestID,
		UserId:            userID,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to fetch updated callback request: %w", err)
	}
	return mapCallbackRequestFromProto(cb), nil
}

// SendMessage is the resolver for the sendMessage field.
func (r *mutationResolver) SendMessage(ctx context.Context, input model.SendMessageInput) (*model.Message, error) {
	userID := requestctx.UserID(ctx)
	if userID == "" {
		return nil, fmt.Errorf("authentication required")
	}

	msgType := "TEXT"
	if input.MessageType != nil {
		msgType = *input.MessageType
	}

	resp, err := r.Clients.Communication.SendMessage(ctx, &commpb.SendMessageRequest{
		ConversationId: input.ConversationID,
		SenderType:     "USER",
		SenderRefId:    userID,
		MessageType:    msgType,
		Content:        input.Content,
	})
	if err != nil {
		r.Log.Error("failed to send message", zap.Error(err), zap.String("user_id", userID))
		return nil, fmt.Errorf("failed to send message: %w", err)
	}
	return mapMessageFromProto(resp), nil
}

// BlockServiceProvider is the resolver for the blockServiceProvider field.
func (r *mutationResolver) BlockServiceProvider(ctx context.Context, serviceProviderID string, reason *string) (bool, error) {
	userID := requestctx.UserID(ctx)
	if userID == "" {
		return false, fmt.Errorf("authentication required")
	}

	resp, err := r.Clients.User.BlockServiceProvider(ctx, &userpb.BlockServiceProviderRequest{
		UserId:            userID,
		ServiceProviderId: serviceProviderID,
	})
	if err != nil {
		r.Log.Error("failed to block service provider", zap.Error(err), zap.String("user_id", userID))
		return false, fmt.Errorf("failed to block service provider: %w", err)
	}
	return resp.Success, nil
}

// UnblockServiceProvider is the resolver for the unblockServiceProvider field.
func (r *mutationResolver) UnblockServiceProvider(ctx context.Context, serviceProviderID string) (bool, error) {
	userID := requestctx.UserID(ctx)
	if userID == "" {
		return false, fmt.Errorf("authentication required")
	}

	resp, err := r.Clients.User.UnblockServiceProvider(ctx, &userpb.UnblockServiceProviderRequest{
		UserId:            userID,
		ServiceProviderId: serviceProviderID,
	})
	if err != nil {
		r.Log.Error("failed to unblock service provider", zap.Error(err), zap.String("user_id", userID))
		return false, fmt.Errorf("failed to unblock service provider: %w", err)
	}
	return resp.Success, nil
}

// ReportSpam is the resolver for the reportSpam field.
func (r *mutationResolver) ReportSpam(ctx context.Context, input model.ReportSpamInput) (bool, error) {
	userID := requestctx.UserID(ctx)
	if userID == "" {
		return false, fmt.Errorf("authentication required")
	}

	resp, err := r.Clients.Communication.ReportSpam(ctx, &commpb.ReportSpamRequest{
		UserId:            userID,
		OrganizationId:    input.ServiceProviderID,
		NotificationId:    strOrEmpty(input.NotificationID),
		CallbackRequestId: strOrEmpty(input.CallbackRequestID),
		Reason:            input.Reason,
		Details:           strOrEmpty(input.Details),
	})
	if err != nil {
		r.Log.Error("failed to report spam", zap.Error(err), zap.String("user_id", userID))
		return false, fmt.Errorf("failed to report spam: %w", err)
	}
	return resp.Success, nil
}

// MarkNotificationAsRead is the resolver for the markNotificationAsRead field.
func (r *mutationResolver) MarkNotificationAsRead(ctx context.Context, id string) (bool, error) {
	userID := requestctx.UserID(ctx)
	if userID == "" {
		return false, fmt.Errorf("authentication required")
	}

	resp, err := r.Clients.Notification.MarkAsRead(ctx, &notifpb.MarkAsReadRequest{
		NotificationId: id,
		UserId:         userID,
	})
	if err != nil {
		r.Log.Error("failed to mark notification as read", zap.Error(err), zap.String("user_id", userID))
		return false, fmt.Errorf("failed to mark notification as read: %w", err)
	}
	return resp.Success, nil
}

// ArchiveNotification is the resolver for the archiveNotification field.
func (r *mutationResolver) ArchiveNotification(ctx context.Context, id string) (bool, error) {
	userID := requestctx.UserID(ctx)
	if userID == "" {
		return false, fmt.Errorf("authentication required")
	}

	resp, err := r.Clients.Notification.ArchiveNotification(ctx, &notifpb.ArchiveNotificationRequest{
		NotificationId: id,
		UserId:         userID,
	})
	if err != nil {
		r.Log.Error("failed to archive notification", zap.Error(err), zap.String("user_id", userID))
		return false, fmt.Errorf("failed to archive notification: %w", err)
	}
	return resp.Success, nil
}

// UpdateMyProfile is the resolver for the updateMyProfile field.
func (r *mutationResolver) UpdateMyProfile(ctx context.Context, input model.UpdateProfileInput) (*model.UserProfile, error) {
	userID, err := requireCustomerRole(ctx)
	if err != nil {
		return nil, err
	}

	req := &userpb.UpdateUserProfileRequest{UserId: userID}

	// Build full name from first + last
	if input.FirstName != nil || input.LastName != nil {
		first := strOrEmpty(input.FirstName)
		last := strOrEmpty(input.LastName)
		if first != "" && last != "" {
			req.FullName = first + " " + last
		} else if first != "" {
			req.FullName = first
		} else if last != "" {
			req.FullName = last
		}
	}
	if input.AvatarURL != nil {
		req.AvatarUrl = *input.AvatarURL
	}
	if input.Timezone != nil {
		req.Timezone = *input.Timezone
	}
	if input.Language != nil {
		req.Language = *input.Language
	}

	_, err = r.Clients.User.UpdateUserProfile(ctx, req)
	if err != nil {
		r.Log.Error("failed to update profile", zap.Error(err), zap.String("user_id", userID))
		return nil, fmt.Errorf("failed to update profile: %w", err)
	}

	// Re-fetch profile to return updated data
	profile, err := r.Clients.User.GetUserProfile(ctx, &userpb.GetUserProfileRequest{UserId: userID})
	if err != nil {
		return nil, fmt.Errorf("failed to fetch updated profile: %w", err)
	}
	return mapUserProfileFromProto(profile), nil
}

// UpdateMyAvatar is the resolver for the updateMyAvatar field.
func (r *mutationResolver) UpdateMyAvatar(ctx context.Context, url string) (*model.UserProfile, error) {
	userID, err := requireCustomerRole(ctx)
	if err != nil {
		return nil, err
	}

	_, err = r.Clients.User.UpdateUserProfile(ctx, &userpb.UpdateUserProfileRequest{
		UserId:    userID,
		AvatarUrl: url,
	})
	if err != nil {
		r.Log.Error("failed to update avatar", zap.Error(err), zap.String("user_id", userID))
		return nil, fmt.Errorf("failed to update avatar: %w", err)
	}

	profile, err := r.Clients.User.GetUserProfile(ctx, &userpb.GetUserProfileRequest{UserId: userID})
	if err != nil {
		return nil, fmt.Errorf("failed to fetch updated profile: %w", err)
	}
	return mapUserProfileFromProto(profile), nil
}

// MarkAllNotificationsRead is the resolver for the markAllNotificationsRead field.
func (r *mutationResolver) MarkAllNotificationsRead(ctx context.Context) (bool, error) {
	userID, err := requireCustomerRole(ctx)
	if err != nil {
		return false, err
	}

	// Fetch all unread notifications
	listResp, err := r.Clients.Notification.ListNotifications(ctx, &notifpb.ListNotificationsRequest{
		UserId: userID,
		Status: "UNREAD",
		Limit:  500,
		Offset: 0,
	})
	if err != nil {
		r.Log.Error("failed to list unread notifications", zap.Error(err), zap.String("user_id", userID))
		return false, fmt.Errorf("failed to list unread notifications: %w", err)
	}

	// Mark each as read
	for _, n := range listResp.Notifications {
		_, err := r.Clients.Notification.MarkAsRead(ctx, &notifpb.MarkAsReadRequest{
			NotificationId: n.Id,
			UserId:         userID,
		})
		if err != nil {
			r.Log.Error("failed to mark notification as read",
				zap.Error(err),
				zap.String("notification_id", n.Id),
				zap.String("user_id", userID),
			)
		}
	}

	return true, nil
}

// SendNotification is the resolver for the sendNotification field.
func (r *mutationResolver) SendNotification(ctx context.Context, input model.SendNotificationInput) (*model.Notification, error) {
	_, spID, err := requireProviderRole(ctx)
	if err != nil {
		return nil, err
	}

	priority := "NORMAL"
	if input.Priority != nil {
		priority = string(*input.Priority)
	}

	resp, err := r.Clients.Notification.CreateNotification(ctx, &notifpb.CreateNotificationRequest{
		UserId:            input.UserID,
		ServiceProviderId: spID,
		Category:          string(input.Category),
		Title:             input.Title,
		Body:              input.Body,
		Priority:          priority,
	})
	if err != nil {
		r.Log.Error("failed to send notification", zap.Error(err))
		return nil, fmt.Errorf("failed to send notification: %w", err)
	}

	return &model.Notification{
		ID:       resp.NotificationId,
		Category: input.Category,
		Title:    input.Title,
		Body:     input.Body,
		Priority: priority,
		Status:   resp.Status,
	}, nil
}

// CreateCallbackRequest is the resolver for the createCallbackRequest field.
func (r *mutationResolver) CreateCallbackRequest(ctx context.Context, input model.CreateCallbackRequestInput) (*model.CallbackRequest, error) {
	userID, spID, err := requireProviderRole(ctx)
	if err != nil {
		return nil, err
	}

	resp, err := r.Clients.Communication.CreateCallbackRequest(ctx, &commpb.CreateCallbackRequestRequest{
		UserId:              input.UserID,
		ServiceProviderId:   spID,
		RequestedBySpUserId: userID,
		Reason:              input.Reason,
		Details:             strOrEmpty(input.Details),
	})
	if err != nil {
		r.Log.Error("failed to create callback request", zap.Error(err))
		return nil, fmt.Errorf("failed to create callback request: %w", err)
	}

	return &model.CallbackRequest{
		ID:     resp.CallbackRequestId,
		Reason: input.Reason,
		Status: model.CallbackRequestStatusPending,
	}, nil
}

// CreateBot is the resolver for the createBot field.
func (r *mutationResolver) CreateBot(ctx context.Context, input model.CreateBotInput) (*model.Bot, error) {
	panic(fmt.Errorf("not implemented: CreateBot - createBot"))
}

// UpdateBot is the resolver for the updateBot field.
func (r *mutationResolver) UpdateBot(ctx context.Context, input model.UpdateBotInput) (*model.Bot, error) {
	panic(fmt.Errorf("not implemented: UpdateBot - updateBot"))
}

// DeleteBot is the resolver for the deleteBot field.
func (r *mutationResolver) DeleteBot(ctx context.Context, botID string, serviceProviderID string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteBot - deleteBot"))
}

// UpdateBotConfiguration is the resolver for the updateBotConfiguration field.
func (r *mutationResolver) UpdateBotConfiguration(ctx context.Context, input model.UpdateBotConfigurationInput) (*model.BotConfiguration, error) {
	panic(fmt.Errorf("not implemented: UpdateBotConfiguration - updateBotConfiguration"))
}

// SetBotPermission is the resolver for the setBotPermission field.
func (r *mutationResolver) SetBotPermission(ctx context.Context, input model.SetBotPermissionInput) (bool, error) {
	panic(fmt.Errorf("not implemented: SetBotPermission - setBotPermission"))
}

// AddKnowledgeSource is the resolver for the addKnowledgeSource field.
func (r *mutationResolver) AddKnowledgeSource(ctx context.Context, input model.AddKnowledgeSourceInput) (*model.KnowledgeSource, error) {
	panic(fmt.Errorf("not implemented: AddKnowledgeSource - addKnowledgeSource"))
}

// RemoveKnowledgeSource is the resolver for the removeKnowledgeSource field.
func (r *mutationResolver) RemoveKnowledgeSource(ctx context.Context, knowledgeSourceID string, botID string, serviceProviderID string) (bool, error) {
	panic(fmt.Errorf("not implemented: RemoveKnowledgeSource - removeKnowledgeSource"))
}

// ExecuteBotAction is the resolver for the executeBotAction field.
func (r *mutationResolver) ExecuteBotAction(ctx context.Context, input model.ExecuteBotActionInput) (*model.ExecuteBotActionResult, error) {
	panic(fmt.Errorf("not implemented: ExecuteBotAction - executeBotAction"))
}

// CreateWebhookSubscription is the resolver for the createWebhookSubscription field.
func (r *mutationResolver) CreateWebhookSubscription(ctx context.Context, input model.CreateWebhookSubscriptionInput) (*model.WebhookSubscription, error) {
	panic(fmt.Errorf("not implemented: CreateWebhookSubscription - createWebhookSubscription"))
}

// UpdateWebhookSubscription is the resolver for the updateWebhookSubscription field.
func (r *mutationResolver) UpdateWebhookSubscription(ctx context.Context, input model.UpdateWebhookSubscriptionInput) (*model.WebhookSubscription, error) {
	panic(fmt.Errorf("not implemented: UpdateWebhookSubscription - updateWebhookSubscription"))
}

// DeleteWebhookSubscription is the resolver for the deleteWebhookSubscription field.
func (r *mutationResolver) DeleteWebhookSubscription(ctx context.Context, subscriptionID string, serviceProviderID string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteWebhookSubscription - deleteWebhookSubscription"))
}

// TestWebhookSubscription is the resolver for the testWebhookSubscription field.
func (r *mutationResolver) TestWebhookSubscription(ctx context.Context, subscriptionID string, serviceProviderID string) (*model.TestWebhookResult, error) {
	panic(fmt.Errorf("not implemented: TestWebhookSubscription - testWebhookSubscription"))
}

// RetryWebhookDelivery is the resolver for the retryWebhookDelivery field.
func (r *mutationResolver) RetryWebhookDelivery(ctx context.Context, deliveryID string, serviceProviderID string) (bool, error) {
	panic(fmt.Errorf("not implemented: RetryWebhookDelivery - retryWebhookDelivery"))
}

// CreateAPIKey is the resolver for the createAPIKey field.
func (r *mutationResolver) CreateAPIKey(ctx context.Context, input model.CreateAPIKeyInput) (*model.APIKeyWithSecret, error) {
	panic(fmt.Errorf("not implemented: CreateAPIKey - createAPIKey"))
}

// RevokeAPIKey is the resolver for the revokeAPIKey field.
func (r *mutationResolver) RevokeAPIKey(ctx context.Context, input model.RevokeAPIKeyInput) (bool, error) {
	panic(fmt.Errorf("not implemented: RevokeAPIKey - revokeAPIKey"))
}

// CreateCampaign is the resolver for the createCampaign field.
func (r *mutationResolver) CreateCampaign(ctx context.Context, input model.CreateCampaignInput) (*model.Campaign, error) {
	panic(fmt.Errorf("not implemented: CreateCampaign - createCampaign"))
}

// UpdateCampaign is the resolver for the updateCampaign field.
func (r *mutationResolver) UpdateCampaign(ctx context.Context, input model.UpdateCampaignInput) (*model.Campaign, error) {
	panic(fmt.Errorf("not implemented: UpdateCampaign - updateCampaign"))
}

// CancelCampaign is the resolver for the cancelCampaign field.
func (r *mutationResolver) CancelCampaign(ctx context.Context, campaignID string, serviceProviderID string) (bool, error) {
	panic(fmt.Errorf("not implemented: CancelCampaign - cancelCampaign"))
}

// LaunchCampaign is the resolver for the launchCampaign field.
func (r *mutationResolver) LaunchCampaign(ctx context.Context, campaignID string, serviceProviderID string) (*model.Campaign, error) {
	panic(fmt.Errorf("not implemented: LaunchCampaign - launchCampaign"))
}

// InviteTeamMember is the resolver for the inviteTeamMember field.
func (r *mutationResolver) InviteTeamMember(ctx context.Context, input model.InviteTeamMemberInput) (*model.InviteTeamMemberResult, error) {
	panic(fmt.Errorf("not implemented: InviteTeamMember - inviteTeamMember"))
}

// AcceptInvitation is the resolver for the acceptInvitation field.
func (r *mutationResolver) AcceptInvitation(ctx context.Context, token string) (bool, error) {
	panic(fmt.Errorf("not implemented: AcceptInvitation - acceptInvitation"))
}

// RevokeInvitation is the resolver for the revokeInvitation field.
func (r *mutationResolver) RevokeInvitation(ctx context.Context, invitationID string, serviceProviderID string) (bool, error) {
	panic(fmt.Errorf("not implemented: RevokeInvitation - revokeInvitation"))
}

// ChangeTeamMemberRole is the resolver for the changeTeamMemberRole field.
func (r *mutationResolver) ChangeTeamMemberRole(ctx context.Context, input model.ChangeTeamMemberRoleInput) (bool, error) {
	panic(fmt.Errorf("not implemented: ChangeTeamMemberRole - changeTeamMemberRole"))
}

// RemoveTeamMember is the resolver for the removeTeamMember field.
func (r *mutationResolver) RemoveTeamMember(ctx context.Context, input model.RemoveTeamMemberInput) (bool, error) {
	panic(fmt.Errorf("not implemented: RemoveTeamMember - removeTeamMember"))
}

// CreateAddress is the resolver for the createAddress field.
func (r *mutationResolver) CreateAddress(ctx context.Context, input model.CreateAddressInput) (*model.UserAddress, error) {
	userID, err := requireAnyAuthenticatedRole(ctx)
	if err != nil {
		return nil, err
	}

	isCurrent := false
	if input.IsCurrent != nil {
		isCurrent = *input.IsCurrent
	}

	resp, err := r.Clients.User.CreateAddress(ctx, &userpb.CreateAddressRequest{
		UserId:       userID,
		Label:        input.Label,
		AddressLine1: input.AddressLine1,
		AddressLine2: strOrEmpty(input.AddressLine2),
		City:         input.City,
		State:        strOrEmpty(input.State),
		PostalCode:   strOrEmpty(input.PostalCode),
		Country:      input.Country,
		Latitude:     floatOrZero(input.Latitude),
		Longitude:    floatOrZero(input.Longitude),
		IsCurrent:    isCurrent,
	})
	if err != nil {
		r.Log.Error("failed to create address", zap.Error(err), zap.String("user_id", userID))
		return nil, fmt.Errorf("failed to create address: %w", err)
	}
	return mapUserAddressFromProto(resp), nil
}

// UpdateAddress is the resolver for the updateAddress field.
func (r *mutationResolver) UpdateAddress(ctx context.Context, input model.UpdateAddressInput) (*model.UserAddress, error) {
	userID, err := requireAnyAuthenticatedRole(ctx)
	if err != nil {
		return nil, err
	}

	isCurrent := false
	if input.IsCurrent != nil {
		isCurrent = *input.IsCurrent
	}

	resp, err := r.Clients.User.UpdateAddress(ctx, &userpb.UpdateAddressRequest{
		Id:           input.ID,
		UserId:       userID,
		Label:        strOrEmpty(input.Label),
		AddressLine1: strOrEmpty(input.AddressLine1),
		AddressLine2: strOrEmpty(input.AddressLine2),
		City:         strOrEmpty(input.City),
		State:        strOrEmpty(input.State),
		PostalCode:   strOrEmpty(input.PostalCode),
		Country:      strOrEmpty(input.Country),
		Latitude:     floatOrZero(input.Latitude),
		Longitude:    floatOrZero(input.Longitude),
		IsCurrent:    isCurrent,
	})
	if err != nil {
		r.Log.Error("failed to update address", zap.Error(err), zap.String("user_id", userID))
		return nil, fmt.Errorf("failed to update address: %w", err)
	}
	return mapUserAddressFromProto(resp), nil
}

// DeleteAddress is the resolver for the deleteAddress field.
func (r *mutationResolver) DeleteAddress(ctx context.Context, id string) (bool, error) {
	userID, err := requireAnyAuthenticatedRole(ctx)
	if err != nil {
		return false, err
	}

	_, err = r.Clients.User.DeleteAddress(ctx, &userpb.DeleteAddressRequest{
		Id:     id,
		UserId: userID,
	})
	if err != nil {
		r.Log.Error("failed to delete address", zap.Error(err), zap.String("user_id", userID))
		return false, fmt.Errorf("failed to delete address: %w", err)
	}
	return true, nil
}

// SetCurrentAddress is the resolver for the setCurrentAddress field.
func (r *mutationResolver) SetCurrentAddress(ctx context.Context, id string) (bool, error) {
	userID, err := requireAnyAuthenticatedRole(ctx)
	if err != nil {
		return false, err
	}

	_, err = r.Clients.User.SetCurrentAddress(ctx, &userpb.SetCurrentAddressRequest{
		Id:     id,
		UserId: userID,
	})
	if err != nil {
		r.Log.Error("failed to set current address", zap.Error(err), zap.String("user_id", userID))
		return false, fmt.Errorf("failed to set current address: %w", err)
	}
	return true, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	userID, err := requireAnyAuthenticatedRole(ctx)
	if err != nil {
		return nil, err
	}

	resp, err := r.Clients.User.GetUserProfile(ctx, &userpb.GetUserProfileRequest{UserId: userID})
	if err != nil {
		r.Log.Error("failed to get user profile", zap.Error(err), zap.String("user_id", userID))
		return nil, fmt.Errorf("failed to get user profile: %w", err)
	}
	return mapUserFromProto(resp), nil
}

// DashboardSummary is the resolver for the dashboardSummary field.
func (r *queryResolver) DashboardSummary(ctx context.Context) (*model.DashboardSummary, error) {
	userID, err := requireAnyAuthenticatedRole(ctx)
	if err != nil {
		return nil, err
	}

	// Fetch unread notifications by category
	personal, _ := r.Clients.Notification.ListNotifications(ctx, &notifpb.ListNotificationsRequest{
		UserId: userID, Category: "PERSONAL", Status: "UNREAD", Limit: 0, Offset: 0,
	})
	sp, _ := r.Clients.Notification.ListNotifications(ctx, &notifpb.ListNotificationsRequest{
		UserId: userID, Category: "SERVICE_PROVIDER", Status: "UNREAD", Limit: 0, Offset: 0,
	})
	ads, _ := r.Clients.Notification.ListNotifications(ctx, &notifpb.ListNotificationsRequest{
		UserId: userID, Category: "ADVERTISEMENT", Status: "UNREAD", Limit: 0, Offset: 0,
	})
	callbacks, _ := r.Clients.Communication.ListCallbackRequests(ctx, &commpb.ListCallbackRequestsRequest{
		UserId: userID, Status: "PENDING", Limit: 0, Offset: 0,
	})
	convos, _ := r.Clients.Communication.ListConversations(ctx, &commpb.ListConversationsRequest{
		UserId: userID, Limit: 0, Offset: 0,
	})

	summary := &model.DashboardSummary{}
	if personal != nil {
		summary.UnreadPersonal = int(personal.Total)
	}
	if sp != nil {
		summary.UnreadServiceProvider = int(sp.Total)
	}
	if ads != nil {
		summary.UnreadAdvertisements = int(ads.Total)
	}
	if callbacks != nil {
		summary.PendingCallbackRequests = int(callbacks.Total)
	}
	if convos != nil {
		summary.TotalConversations = int(convos.Total)
	}
	return summary, nil
}

// Notifications is the resolver for the notifications field.
func (r *queryResolver) Notifications(ctx context.Context, category *model.NotificationCategory, status *string, limit *int, offset *int) (*model.NotificationConnection, error) {
	userID, err := requireAnyAuthenticatedRole(ctx)
	if err != nil {
		return nil, err
	}

	cat := ""
	if category != nil {
		cat = string(*category)
	}

	resp, err := r.Clients.Notification.ListNotifications(ctx, &notifpb.ListNotificationsRequest{
		UserId:   userID,
		Category: cat,
		Status:   strOrEmpty(status),
		Limit:    intOrDefault(limit, 20),
		Offset:   intOrDefault(offset, 0),
	})
	if err != nil {
		r.Log.Error("failed to list notifications", zap.Error(err), zap.String("user_id", userID))
		return nil, fmt.Errorf("failed to list notifications: %w", err)
	}
	return mapNotificationConnectionFromProto(resp), nil
}

// Notification is the resolver for the notification field.
func (r *queryResolver) Notification(ctx context.Context, id string) (*model.Notification, error) {
	userID, err := requireAnyAuthenticatedRole(ctx)
	if err != nil {
		return nil, err
	}

	resp, err := r.Clients.Notification.GetNotification(ctx, &notifpb.GetNotificationRequest{
		NotificationId: id,
		UserId:         userID,
	})
	if err != nil {
		r.Log.Error("failed to get notification", zap.Error(err), zap.String("user_id", userID))
		return nil, fmt.Errorf("failed to get notification: %w", err)
	}
	return mapNotificationFromProto(resp), nil
}

// CallbackRequests is the resolver for the callbackRequests field.
func (r *queryResolver) CallbackRequests(ctx context.Context, status *model.CallbackRequestStatus, limit *int, offset *int) (*model.CallbackRequestConnection, error) {
	userID, err := requireAnyAuthenticatedRole(ctx)
	if err != nil {
		return nil, err
	}

	st := ""
	if status != nil {
		st = string(*status)
	}

	resp, err := r.Clients.Communication.ListCallbackRequests(ctx, &commpb.ListCallbackRequestsRequest{
		UserId: userID,
		Status: st,
		Limit:  intOrDefault(limit, 20),
		Offset: intOrDefault(offset, 0),
	})
	if err != nil {
		r.Log.Error("failed to list callback requests", zap.Error(err), zap.String("user_id", userID))
		return nil, fmt.Errorf("failed to list callback requests: %w", err)
	}
	return mapCallbackRequestConnectionFromProto(resp), nil
}

// CallbackRequest is the resolver for the callbackRequest field.
func (r *queryResolver) CallbackRequest(ctx context.Context, id string) (*model.CallbackRequest, error) {
	userID, err := requireAnyAuthenticatedRole(ctx)
	if err != nil {
		return nil, err
	}

	resp, err := r.Clients.Communication.GetCallbackRequest(ctx, &commpb.GetCallbackRequestRequest{
		CallbackRequestId: id,
		UserId:            userID,
	})
	if err != nil {
		r.Log.Error("failed to get callback request", zap.Error(err), zap.String("user_id", userID))
		return nil, fmt.Errorf("failed to get callback request: %w", err)
	}
	return mapCallbackRequestFromProto(resp), nil
}

// Conversations is the resolver for the conversations field.
func (r *queryResolver) Conversations(ctx context.Context, limit *int, offset *int) (*model.ConversationConnection, error) {
	userID, err := requireAnyAuthenticatedRole(ctx)
	if err != nil {
		return nil, err
	}

	resp, err := r.Clients.Communication.ListConversations(ctx, &commpb.ListConversationsRequest{
		UserId: userID,
		Limit:  intOrDefault(limit, 20),
		Offset: intOrDefault(offset, 0),
	})
	if err != nil {
		r.Log.Error("failed to list conversations", zap.Error(err), zap.String("user_id", userID))
		return nil, fmt.Errorf("failed to list conversations: %w", err)
	}
	return mapConversationConnectionFromProto(resp), nil
}

// Conversation is the resolver for the conversation field.
func (r *queryResolver) Conversation(ctx context.Context, id string) (*model.Conversation, error) {
	userID, err := requireAnyAuthenticatedRole(ctx)
	if err != nil {
		return nil, err
	}

	resp, err := r.Clients.Communication.GetConversation(ctx, &commpb.GetConversationRequest{
		ConversationId: id,
		UserId:         userID,
	})
	if err != nil {
		r.Log.Error("failed to get conversation", zap.Error(err), zap.String("user_id", userID))
		return nil, fmt.Errorf("failed to get conversation: %w", err)
	}
	return mapConversationFromProto(resp), nil
}

// ServiceProviders is the resolver for the serviceProviders field.
func (r *queryResolver) ServiceProviders(ctx context.Context, search *string, limit *int, offset *int) ([]*model.ServiceProvider, error) {
	_, err := requireAnyAuthenticatedRole(ctx)
	if err != nil {
		return nil, err
	}

	resp, err := r.Clients.Organization.ListServiceProviders(ctx, &orgpb.ListServiceProvidersRequest{
		Search: strOrEmpty(search),
		Limit:  intOrDefault(limit, 20),
		Offset: intOrDefault(offset, 0),
	})
	if err != nil {
		r.Log.Error("failed to list service providers", zap.Error(err))
		return nil, fmt.Errorf("failed to list service providers: %w", err)
	}
	result := make([]*model.ServiceProvider, len(resp.ServiceProviders))
	for i, sp := range resp.ServiceProviders {
		result[i] = mapServiceProviderFromProto(sp)
	}
	return result, nil
}

// ServiceProvider is the resolver for the serviceProvider field.
func (r *queryResolver) ServiceProvider(ctx context.Context, id string) (*model.ServiceProvider, error) {
	_, err := requireAnyAuthenticatedRole(ctx)
	if err != nil {
		return nil, err
	}

	resp, err := r.Clients.Organization.GetServiceProvider(ctx, &orgpb.GetServiceProviderRequest{
		ServiceProviderId: id,
	})
	if err != nil {
		r.Log.Error("failed to get service provider", zap.Error(err))
		return nil, fmt.Errorf("failed to get service provider: %w", err)
	}
	return mapServiceProviderFromProto(resp), nil
}

// CheckCommunicationPolicy is the resolver for the checkCommunicationPolicy field.
func (r *queryResolver) CheckCommunicationPolicy(ctx context.Context, serviceProviderID string, category model.NotificationCategory, channel string) (*model.PolicyCheckResult, error) {
	panic(fmt.Errorf("not implemented: CheckCommunicationPolicy - checkCommunicationPolicy"))
}

// Bot is the resolver for the bot field.
func (r *queryResolver) Bot(ctx context.Context, id string, serviceProviderID string) (*model.Bot, error) {
	panic(fmt.Errorf("not implemented: Bot - bot"))
}

// Bots is the resolver for the bots field.
func (r *queryResolver) Bots(ctx context.Context, serviceProviderID string, status *model.BotStatus, limit *int, offset *int) (*model.BotConnection, error) {
	panic(fmt.Errorf("not implemented: Bots - bots"))
}

// BotConfiguration is the resolver for the botConfiguration field.
func (r *queryResolver) BotConfiguration(ctx context.Context, botID string, serviceProviderID string) (*model.BotConfiguration, error) {
	panic(fmt.Errorf("not implemented: BotConfiguration - botConfiguration"))
}

// BotPermissions is the resolver for the botPermissions field.
func (r *queryResolver) BotPermissions(ctx context.Context, botID string, serviceProviderID string) ([]*model.BotPermission, error) {
	panic(fmt.Errorf("not implemented: BotPermissions - botPermissions"))
}

// BotKnowledgeSources is the resolver for the botKnowledgeSources field.
func (r *queryResolver) BotKnowledgeSources(ctx context.Context, botID string, serviceProviderID string) ([]*model.KnowledgeSource, error) {
	panic(fmt.Errorf("not implemented: BotKnowledgeSources - botKnowledgeSources"))
}

// BotActionLogs is the resolver for the botActionLogs field.
func (r *queryResolver) BotActionLogs(ctx context.Context, botID string, serviceProviderID string, conversationID *string, limit *int, offset *int) (*model.BotActionLogConnection, error) {
	panic(fmt.Errorf("not implemented: BotActionLogs - botActionLogs"))
}

// BotAnalytics is the resolver for the botAnalytics field.
func (r *queryResolver) BotAnalytics(ctx context.Context, botID string, serviceProviderID string) (*model.BotAnalytics, error) {
	panic(fmt.Errorf("not implemented: BotAnalytics - botAnalytics"))
}

// IndustryProfile is the resolver for the industryProfile field.
func (r *queryResolver) IndustryProfile(ctx context.Context, industryKey string) (*model.IndustryProfile, error) {
	panic(fmt.Errorf("not implemented: IndustryProfile - industryProfile"))
}

// IndustryProfiles is the resolver for the industryProfiles field.
func (r *queryResolver) IndustryProfiles(ctx context.Context, activeOnly *bool, limit *int, offset *int) (*model.IndustryProfileConnection, error) {
	panic(fmt.Errorf("not implemented: IndustryProfiles - industryProfiles"))
}

// WebhookSubscription is the resolver for the webhookSubscription field.
func (r *queryResolver) WebhookSubscription(ctx context.Context, id string, serviceProviderID string) (*model.WebhookSubscription, error) {
	panic(fmt.Errorf("not implemented: WebhookSubscription - webhookSubscription"))
}

// WebhookSubscriptions is the resolver for the webhookSubscriptions field.
func (r *queryResolver) WebhookSubscriptions(ctx context.Context, serviceProviderID string, status *model.WebhookSubscriptionStatus, limit *int, offset *int) (*model.WebhookSubscriptionConnection, error) {
	panic(fmt.Errorf("not implemented: WebhookSubscriptions - webhookSubscriptions"))
}

// WebhookDeliveries is the resolver for the webhookDeliveries field.
func (r *queryResolver) WebhookDeliveries(ctx context.Context, subscriptionID string, serviceProviderID string, status *model.WebhookDeliveryStatus, limit *int, offset *int) (*model.WebhookDeliveryConnection, error) {
	panic(fmt.Errorf("not implemented: WebhookDeliveries - webhookDeliveries"))
}

// APIKeys is the resolver for the apiKeys field.
func (r *queryResolver) APIKeys(ctx context.Context, serviceProviderID string) (*model.APIKeyConnection, error) {
	panic(fmt.Errorf("not implemented: APIKeys - apiKeys"))
}

// Campaign is the resolver for the campaign field.
func (r *queryResolver) Campaign(ctx context.Context, id string, serviceProviderID string) (*model.Campaign, error) {
	panic(fmt.Errorf("not implemented: Campaign - campaign"))
}

// Campaigns is the resolver for the campaigns field.
func (r *queryResolver) Campaigns(ctx context.Context, serviceProviderID string, status *model.CampaignStatus, limit *int, offset *int) (*model.CampaignConnection, error) {
	panic(fmt.Errorf("not implemented: Campaigns - campaigns"))
}

// PreviewCampaignPolicy is the resolver for the previewCampaignPolicy field.
func (r *queryResolver) PreviewCampaignPolicy(ctx context.Context, input model.PreviewCampaignPolicyInput) (*model.CampaignPolicyPreview, error) {
	panic(fmt.Errorf("not implemented: PreviewCampaignPolicy - previewCampaignPolicy"))
}

// DashboardAnalytics is the resolver for the dashboardAnalytics field.
func (r *queryResolver) DashboardAnalytics(ctx context.Context, serviceProviderID string, from time.Time, to time.Time) (*model.DashboardAnalytics, error) {
	panic(fmt.Errorf("not implemented: DashboardAnalytics - dashboardAnalytics"))
}

// DailyAnalytics is the resolver for the dailyAnalytics field.
func (r *queryResolver) DailyAnalytics(ctx context.Context, serviceProviderID string, from time.Time, to time.Time) ([]*model.DailyAnalyticsEntry, error) {
	panic(fmt.Errorf("not implemented: DailyAnalytics - dailyAnalytics"))
}

// NotificationAnalytics is the resolver for the notificationAnalytics field.
func (r *queryResolver) NotificationAnalytics(ctx context.Context, serviceProviderID string, from time.Time, to time.Time) (*model.NotificationAnalytics, error) {
	panic(fmt.Errorf("not implemented: NotificationAnalytics - notificationAnalytics"))
}

// CallbackAnalytics is the resolver for the callbackAnalytics field.
func (r *queryResolver) CallbackAnalytics(ctx context.Context, serviceProviderID string, from time.Time, to time.Time) (*model.CallbackAnalytics, error) {
	panic(fmt.Errorf("not implemented: CallbackAnalytics - callbackAnalytics"))
}

// CampaignAnalytics is the resolver for the campaignAnalytics field.
func (r *queryResolver) CampaignAnalytics(ctx context.Context, serviceProviderID string, campaignID string, from *time.Time, to *time.Time) (*model.CampaignAnalytics, error) {
	panic(fmt.Errorf("not implemented: CampaignAnalytics - campaignAnalytics"))
}

// BotPerformanceAnalytics is the resolver for the botPerformanceAnalytics field.
func (r *queryResolver) BotPerformanceAnalytics(ctx context.Context, serviceProviderID string, botID string, from *time.Time, to *time.Time) (*model.BotPerformanceAnalytics, error) {
	panic(fmt.Errorf("not implemented: BotPerformanceAnalytics - botPerformanceAnalytics"))
}

// TeamMembers is the resolver for the teamMembers field.
func (r *queryResolver) TeamMembers(ctx context.Context, serviceProviderID string, limit *int, offset *int) (*model.TeamMemberConnection, error) {
	panic(fmt.Errorf("not implemented: TeamMembers - teamMembers"))
}

// PendingInvitations is the resolver for the pendingInvitations field.
func (r *queryResolver) PendingInvitations(ctx context.Context, serviceProviderID string, limit *int, offset *int) (*model.InvitationConnection, error) {
	panic(fmt.Errorf("not implemented: PendingInvitations - pendingInvitations"))
}

// MyServiceProviders is the resolver for the myServiceProviders field.
func (r *queryResolver) MyServiceProviders(ctx context.Context, limit *int, offset *int, search *string) (*model.ServiceProviderConnection, error) {
	userID, err := requireAnyAuthenticatedRole(ctx)
	if err != nil {
		return nil, err
	}

	resp, err := r.Clients.Organization.ListServiceProviders(ctx, &orgpb.ListServiceProvidersRequest{
		Search: strOrEmpty(search),
		Limit:  intOrDefault(limit, 20),
		Offset: intOrDefault(offset, 0),
	})
	if err != nil {
		r.Log.Error("failed to list user service providers", zap.Error(err), zap.String("user_id", userID))
		return nil, fmt.Errorf("failed to list service providers: %w", err)
	}
	return mapServiceProviderConnectionFromProto(resp), nil
}

// MyProfile is the resolver for the myProfile field.
func (r *queryResolver) MyProfile(ctx context.Context) (*model.UserProfile, error) {
	userID, err := requireCustomerRole(ctx)
	if err != nil {
		return nil, err
	}

	resp, err := r.Clients.User.GetUserProfile(ctx, &userpb.GetUserProfileRequest{UserId: userID})
	if err != nil {
		r.Log.Error("failed to get user profile", zap.Error(err), zap.String("user_id", userID))
		return nil, fmt.Errorf("failed to get user profile: %w", err)
	}
	return mapUserProfileFromProto(resp), nil
}

// MyNotifications is the resolver for the myNotifications field.
func (r *queryResolver) MyNotifications(ctx context.Context, limit *int, offset *int, category *model.NotificationCategory, status *string) (*model.NotificationConnection, error) {
	userID, err := requireCustomerRole(ctx)
	if err != nil {
		return nil, err
	}

	cat := ""
	if category != nil {
		cat = string(*category)
	}

	resp, err := r.Clients.Notification.ListNotifications(ctx, &notifpb.ListNotificationsRequest{
		UserId:   userID,
		Category: cat,
		Status:   strOrEmpty(status),
		Limit:    intOrDefault(limit, 20),
		Offset:   intOrDefault(offset, 0),
	})
	if err != nil {
		r.Log.Error("failed to list notifications", zap.Error(err), zap.String("user_id", userID))
		return nil, fmt.Errorf("failed to list notifications: %w", err)
	}
	return mapNotificationConnectionFromProto(resp), nil
}

// MyCallbackRequests is the resolver for the myCallbackRequests field.
func (r *queryResolver) MyCallbackRequests(ctx context.Context, limit *int, offset *int, status *model.CallbackRequestStatus) (*model.CallbackRequestConnection, error) {
	userID, err := requireCustomerRole(ctx)
	if err != nil {
		return nil, err
	}

	st := ""
	if status != nil {
		st = string(*status)
	}

	resp, err := r.Clients.Communication.ListCallbackRequests(ctx, &commpb.ListCallbackRequestsRequest{
		UserId: userID,
		Status: st,
		Limit:  intOrDefault(limit, 20),
		Offset: intOrDefault(offset, 0),
	})
	if err != nil {
		r.Log.Error("failed to list callback requests", zap.Error(err), zap.String("user_id", userID))
		return nil, fmt.Errorf("failed to list callback requests: %w", err)
	}
	return mapCallbackRequestConnectionFromProto(resp), nil
}

// MyConversations is the resolver for the myConversations field.
func (r *queryResolver) MyConversations(ctx context.Context, limit *int, offset *int, status *model.ConversationStatus) (*model.ConversationConnection, error) {
	userID, err := requireCustomerRole(ctx)
	if err != nil {
		return nil, err
	}

	resp, err := r.Clients.Communication.ListConversations(ctx, &commpb.ListConversationsRequest{
		UserId: userID,
		Limit:  intOrDefault(limit, 20),
		Offset: intOrDefault(offset, 0),
	})
	if err != nil {
		r.Log.Error("failed to list conversations", zap.Error(err), zap.String("user_id", userID))
		return nil, fmt.Errorf("failed to list conversations: %w", err)
	}
	return mapConversationConnectionFromProto(resp), nil
}

// MyDocuments is the resolver for the myDocuments field.
func (r *queryResolver) MyDocuments(ctx context.Context, limit *int, offset *int, serviceProviderID *string, classification *string) (*model.DocumentConnection, error) {
	userID, err := requireCustomerRole(ctx)
	if err != nil {
		return nil, err
	}

	resp, err := r.Clients.Communication.ListDocumentShares(ctx, &commpb.ListDocumentSharesRequest{
		UserId: userID,
		Limit:  intOrDefault(limit, 20),
		Offset: intOrDefault(offset, 0),
	})
	if err != nil {
		r.Log.Error("failed to list documents", zap.Error(err), zap.String("user_id", userID))
		return nil, fmt.Errorf("failed to list documents: %w", err)
	}
	return mapDocumentConnectionFromProto(resp), nil
}

// MyPrivacyPreferences is the resolver for the myPrivacyPreferences field.
func (r *queryResolver) MyPrivacyPreferences(ctx context.Context) (*model.PrivacyPreference, error) {
	userID, err := requireCustomerRole(ctx)
	if err != nil {
		return nil, err
	}

	resp, err := r.Clients.User.GetPrivacyPreference(ctx, &userpb.GetPrivacyPreferenceRequest{UserId: userID})
	if err != nil {
		r.Log.Error("failed to get privacy preferences", zap.Error(err), zap.String("user_id", userID))
		return nil, fmt.Errorf("failed to get privacy preferences: %w", err)
	}
	return mapPrivacyPreferenceFromProto(resp), nil
}

// MyDNDRules is the resolver for the myDNDRules field.
func (r *queryResolver) MyDNDRules(ctx context.Context) ([]*model.DNDRule, error) {
	userID, err := requireCustomerRole(ctx)
	if err != nil {
		return nil, err
	}

	resp, err := r.Clients.User.ListDNDRules(ctx, &userpb.ListDNDRulesRequest{UserId: userID})
	if err != nil {
		r.Log.Error("failed to list DND rules", zap.Error(err), zap.String("user_id", userID))
		return nil, fmt.Errorf("failed to list DND rules: %w", err)
	}

	rules := make([]*model.DNDRule, len(resp.Rules))
	for i, r := range resp.Rules {
		rules[i] = mapDNDRuleFromProto(r)
	}
	return rules, nil
}

// MyAvailabilitySlots is the resolver for the myAvailabilitySlots field.
func (r *queryResolver) MyAvailabilitySlots(ctx context.Context) ([]*model.AvailabilitySlot, error) {
	userID, err := requireCustomerRole(ctx)
	if err != nil {
		return nil, err
	}

	resp, err := r.Clients.User.ListAvailabilitySlots(ctx, &userpb.ListAvailabilitySlotsRequest{UserId: userID})
	if err != nil {
		r.Log.Error("failed to list availability slots", zap.Error(err), zap.String("user_id", userID))
		return nil, fmt.Errorf("failed to list availability slots: %w", err)
	}

	slots := make([]*model.AvailabilitySlot, len(resp.Slots))
	for i, s := range resp.Slots {
		slots[i] = mapAvailabilitySlotFromProto(s)
	}
	return slots, nil
}

// MyBlockedProviders is the resolver for the myBlockedProviders field.
func (r *queryResolver) MyBlockedProviders(ctx context.Context, limit *int, offset *int) (*model.BlockedProviderConnection, error) {
	userID, err := requireCustomerRole(ctx)
	if err != nil {
		return nil, err
	}

	resp, err := r.Clients.User.ListBlockedServiceProviders(ctx, &userpb.ListBlockedServiceProvidersRequest{
		UserId: userID,
	})
	if err != nil {
		r.Log.Error("failed to list blocked providers", zap.Error(err), zap.String("user_id", userID))
		return nil, fmt.Errorf("failed to list blocked providers: %w", err)
	}

	// The proto returns a list of IDs — look up each SP
	nodes := make([]*model.BlockedProvider, 0, len(resp.ServiceProviderIds))
	for _, spID := range resp.ServiceProviderIds {
		sp, err := r.Clients.Organization.GetServiceProvider(ctx, &orgpb.GetServiceProviderRequest{
			ServiceProviderId: spID,
		})
		if err != nil {
			r.Log.Error("failed to get blocked SP details", zap.Error(err), zap.String("sp_id", spID))
			continue
		}
		nodes = append(nodes, &model.BlockedProvider{
			ServiceProvider: mapServiceProviderFromProto(sp),
			BlockedAt:       time.Now(), // Proto doesn't carry blocked_at — use current time as fallback
		})
	}

	// Apply manual pagination since the proto doesn't support it
	lim := int(intOrDefault(limit, 20))
	off := int(intOrDefault(offset, 0))
	total := len(nodes)
	if off > total {
		off = total
	}
	end := off + lim
	if end > total {
		end = total
	}

	return &model.BlockedProviderConnection{
		Nodes:      nodes[off:end],
		TotalCount: total,
	}, nil
}

// MyDashboardSummary is the resolver for the myDashboardSummary field.
func (r *queryResolver) MyDashboardSummary(ctx context.Context) (*model.CustomerDashboardSummary, error) {
	userID, err := requireCustomerRole(ctx)
	if err != nil {
		return nil, err
	}

	summary := &model.CustomerDashboardSummary{}

	// Unread notifications count
	if notifs, err := r.Clients.Notification.ListNotifications(ctx, &notifpb.ListNotificationsRequest{
		UserId: userID, Status: "UNREAD", Limit: 0, Offset: 0,
	}); err == nil {
		summary.UnreadNotifications = int(notifs.Total)
	}

	// Pending callbacks count
	if cbs, err := r.Clients.Communication.ListCallbackRequests(ctx, &commpb.ListCallbackRequestsRequest{
		UserId: userID, Status: "PENDING", Limit: 0, Offset: 0,
	}); err == nil {
		summary.PendingCallbacks = int(cbs.Total)
	}

	// Active conversations count
	if convos, err := r.Clients.Communication.ListConversations(ctx, &commpb.ListConversationsRequest{
		UserId: userID, Limit: 0, Offset: 0,
	}); err == nil {
		summary.ActiveConversations = int(convos.Total)
	}

	// Shared documents count
	if docs, err := r.Clients.Communication.ListDocumentShares(ctx, &commpb.ListDocumentSharesRequest{
		UserId: userID, Limit: 0, Offset: 0,
	}); err == nil {
		summary.SharedDocuments = int(docs.Total)
	}

	// Blocked providers count
	if blocked, err := r.Clients.User.ListBlockedServiceProviders(ctx, &userpb.ListBlockedServiceProvidersRequest{
		UserId: userID,
	}); err == nil {
		summary.BlockedProviders = len(blocked.ServiceProviderIds)
	}

	// DND active
	if dnd, err := r.Clients.User.ListDNDRules(ctx, &userpb.ListDNDRulesRequest{
		UserId: userID,
	}); err == nil {
		for _, rule := range dnd.Rules {
			if rule.IsActive {
				summary.DndActive = true
				break
			}
		}
	}

	return summary, nil
}

// ServiceProviderDirectory is the resolver for the serviceProviderDirectory field.
func (r *queryResolver) ServiceProviderDirectory(ctx context.Context, limit *int, offset *int, search *string, industry *string) (*model.ServiceProviderConnection, error) {
	_, err := requireAnyAuthenticatedRole(ctx)
	if err != nil {
		return nil, err
	}

	req := &orgpb.ListServiceProvidersRequest{
		Search:             strOrEmpty(search),
		VerificationStatus: "VERIFIED",
		Limit:              intOrDefault(limit, 20),
		Offset:             intOrDefault(offset, 0),
	}

	resp, err := r.Clients.Organization.ListServiceProviders(ctx, req)
	if err != nil {
		r.Log.Error("failed to list service provider directory", zap.Error(err))
		return nil, fmt.Errorf("failed to list service provider directory: %w", err)
	}
	return mapServiceProviderConnectionFromProto(resp), nil
}

// FollowedServiceProviders is the resolver for the followedServiceProviders field.
func (r *queryResolver) FollowedServiceProviders(ctx context.Context, limit *int, offset *int, search *string) (*model.ServiceProviderConnection, error) {
	userID, err := requireAnyAuthenticatedRole(ctx)
	if err != nil {
		return nil, err
	}

	lim := intOrDefault(limit, 20)
	off := intOrDefault(offset, 0)

	query := `SELECT sp.id, COALESCE(sp.slug, sp.id::text), sp.name, sp.legal_name, sp.industry,
	                 sp.description, sp.verification_status, sp.status, sp.website,
	                 sp.address, sp.city, sp.state, sp.country, sp.postal_code, sp.latitude, sp.longitude
	          FROM customer_sp_relations csr
	          JOIN service_providers sp ON sp.id = csr.service_provider_id
	          WHERE csr.user_id = $1 AND csr.status = 'ACTIVE'`
	countQuery := `SELECT COUNT(*) FROM customer_sp_relations csr
	               JOIN service_providers sp ON sp.id = csr.service_provider_id
	               WHERE csr.user_id = $1 AND csr.status = 'ACTIVE'`
	args := []interface{}{userID}
	countArgs := []interface{}{userID}
	idx := 2

	if s := strOrEmpty(search); s != "" {
		pattern := "%" + s + "%"
		clause := fmt.Sprintf(" AND sp.name ILIKE $%d", idx)
		query += clause
		countQuery += clause
		args = append(args, pattern)
		countArgs = append(countArgs, pattern)
		idx++
	}

	var total int
	if err := r.DB.QueryRowContext(ctx, countQuery, countArgs...).Scan(&total); err != nil {
		r.Log.Error("failed to count followed providers", zap.Error(err), zap.String("user_id", userID))
		return nil, fmt.Errorf("failed to count followed providers: %w", err)
	}

	query += fmt.Sprintf(" ORDER BY csr.created_at DESC LIMIT $%d OFFSET $%d", idx, idx+1)
	args = append(args, lim, off)

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		r.Log.Error("failed to list followed providers", zap.Error(err), zap.String("user_id", userID))
		return nil, fmt.Errorf("failed to list followed providers: %w", err)
	}
	defer rows.Close()

	var nodes []*model.ServiceProvider
	for rows.Next() {
		var sp model.ServiceProvider
		var legalName, description, website, address, city, state, country, postalCode sql.NullString
		var lat, lng sql.NullFloat64
		if err := rows.Scan(&sp.ID, &sp.Slug, &sp.Name, &legalName, &sp.Industry,
			&description, &sp.VerificationStatus, &sp.Status, &website,
			&address, &city, &state, &country, &postalCode, &lat, &lng); err != nil {
			return nil, fmt.Errorf("scan followed provider: %w", err)
		}
		if legalName.Valid {
			sp.LegalName = &legalName.String
		}
		if description.Valid {
			sp.Description = &description.String
		}
		if website.Valid {
			sp.Website = &website.String
		}
		if address.Valid {
			sp.Address = &address.String
		}
		if city.Valid {
			sp.City = &city.String
		}
		if state.Valid {
			sp.State = &state.String
		}
		if country.Valid {
			sp.Country = &country.String
		}
		if postalCode.Valid {
			sp.PostalCode = &postalCode.String
		}
		if lat.Valid {
			sp.Latitude = &lat.Float64
		}
		if lng.Valid {
			sp.Longitude = &lng.Float64
		}
		nodes = append(nodes, &sp)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate followed providers: %w", err)
	}

	return &model.ServiceProviderConnection{
		Nodes:      nodes,
		TotalCount: total,
	}, nil
}

// NearbyServiceProviders is the resolver for the nearbyServiceProviders field.
func (r *queryResolver) NearbyServiceProviders(ctx context.Context, latitude float64, longitude float64, radiusKm *float64, limit *int, offset *int) (*model.ServiceProviderConnection, error) {
	_, err := requireAnyAuthenticatedRole(ctx)
	if err != nil {
		return nil, err
	}

	radius := 25.0
	if radiusKm != nil {
		radius = *radiusKm
	}
	lim := intOrDefault(limit, 20)
	off := intOrDefault(offset, 0)

	// Haversine distance in km
	const haversine = `(6371 * acos(
		cos(radians($1)) * cos(radians(latitude)) *
		cos(radians(longitude) - radians($2)) +
		sin(radians($1)) * sin(radians(latitude))
	))`

	countQuery := fmt.Sprintf(`SELECT COUNT(*) FROM service_providers
		WHERE latitude IS NOT NULL AND longitude IS NOT NULL
		AND verification_status = 'VERIFIED' AND status = 'ACTIVE'
		AND %s <= $3`, haversine)

	var total int
	if err := r.DB.QueryRowContext(ctx, countQuery, latitude, longitude, radius).Scan(&total); err != nil {
		r.Log.Error("failed to count nearby providers", zap.Error(err))
		return nil, fmt.Errorf("failed to count nearby providers: %w", err)
	}

	query := fmt.Sprintf(`SELECT id, COALESCE(slug, id::text), name, legal_name, industry,
		description, verification_status, status, website,
		address, city, state, country, postal_code, latitude, longitude,
		%s AS distance_km
		FROM service_providers
		WHERE latitude IS NOT NULL AND longitude IS NOT NULL
		AND verification_status = 'VERIFIED' AND status = 'ACTIVE'
		AND %s <= $3
		ORDER BY distance_km ASC
		LIMIT $4 OFFSET $5`, haversine, haversine)

	rows, err := r.DB.QueryContext(ctx, query, latitude, longitude, radius, lim, off)
	if err != nil {
		r.Log.Error("failed to query nearby providers", zap.Error(err))
		return nil, fmt.Errorf("failed to query nearby providers: %w", err)
	}
	defer rows.Close()

	var nodes []*model.ServiceProvider
	for rows.Next() {
		var sp model.ServiceProvider
		var legalName, description, website, address, city, state, country, postalCode sql.NullString
		var lat, lng sql.NullFloat64
		var distKm float64
		if err := rows.Scan(&sp.ID, &sp.Slug, &sp.Name, &legalName, &sp.Industry,
			&description, &sp.VerificationStatus, &sp.Status, &website,
			&address, &city, &state, &country, &postalCode, &lat, &lng,
			&distKm); err != nil {
			return nil, fmt.Errorf("scan nearby provider: %w", err)
		}
		if legalName.Valid {
			sp.LegalName = &legalName.String
		}
		if description.Valid {
			sp.Description = &description.String
		}
		if website.Valid {
			sp.Website = &website.String
		}
		if address.Valid {
			sp.Address = &address.String
		}
		if city.Valid {
			sp.City = &city.String
		}
		if state.Valid {
			sp.State = &state.String
		}
		if country.Valid {
			sp.Country = &country.String
		}
		if postalCode.Valid {
			sp.PostalCode = &postalCode.String
		}
		if lat.Valid {
			sp.Latitude = &lat.Float64
		}
		if lng.Valid {
			sp.Longitude = &lng.Float64
		}
		nodes = append(nodes, &sp)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate nearby providers: %w", err)
	}

	return &model.ServiceProviderConnection{
		Nodes:      nodes,
		TotalCount: total,
	}, nil
}

// MyAddresses is the resolver for the myAddresses field.
func (r *queryResolver) MyAddresses(ctx context.Context) ([]*model.UserAddress, error) {
	userID, err := requireAnyAuthenticatedRole(ctx)
	if err != nil {
		return nil, err
	}

	resp, err := r.Clients.User.ListAddresses(ctx, &userpb.ListAddressesRequest{
		UserId: userID,
	})
	if err != nil {
		r.Log.Error("failed to list addresses", zap.Error(err), zap.String("user_id", userID))
		return nil, fmt.Errorf("failed to list addresses: %w", err)
	}

	result := make([]*model.UserAddress, len(resp.Addresses))
	for i, addr := range resp.Addresses {
		result[i] = mapUserAddressFromProto(addr)
	}
	return result, nil
}

// MyCurrentAddress is the resolver for the myCurrentAddress field.
func (r *queryResolver) MyCurrentAddress(ctx context.Context) (*model.UserAddress, error) {
	userID, err := requireAnyAuthenticatedRole(ctx)
	if err != nil {
		return nil, err
	}

	resp, err := r.Clients.User.GetCurrentAddress(ctx, &userpb.GetCurrentAddressRequest{
		UserId: userID,
	})
	if err != nil {
		r.Log.Error("failed to get current address", zap.Error(err), zap.String("user_id", userID))
		return nil, fmt.Errorf("failed to get current address: %w", err)
	}
	return mapUserAddressFromProto(resp), nil
}

// NotificationReceived is the resolver for the notificationReceived field.
func (r *subscriptionResolver) NotificationReceived(ctx context.Context) (<-chan *model.Notification, error) {
	panic(fmt.Errorf("not implemented: NotificationReceived - notificationReceived"))
}

// CallbackRequestUpdated is the resolver for the callbackRequestUpdated field.
func (r *subscriptionResolver) CallbackRequestUpdated(ctx context.Context, id string) (<-chan *model.CallbackRequest, error) {
	panic(fmt.Errorf("not implemented: CallbackRequestUpdated - callbackRequestUpdated"))
}

// MessageReceived is the resolver for the messageReceived field.
func (r *subscriptionResolver) MessageReceived(ctx context.Context, conversationID string) (<-chan *model.Message, error) {
	panic(fmt.Errorf("not implemented: MessageReceived - messageReceived"))
}

// ProviderNotificationDelivered is the resolver for the providerNotificationDelivered field.
func (r *subscriptionResolver) ProviderNotificationDelivered(ctx context.Context, serviceProviderID string) (<-chan *model.Notification, error) {
	panic(fmt.Errorf("not implemented: ProviderNotificationDelivered - providerNotificationDelivered"))
}

// ProviderCallbackRequestCreated is the resolver for the providerCallbackRequestCreated field.
func (r *subscriptionResolver) ProviderCallbackRequestCreated(ctx context.Context, serviceProviderID string) (<-chan *model.CallbackRequest, error) {
	panic(fmt.Errorf("not implemented: ProviderCallbackRequestCreated - providerCallbackRequestCreated"))
}

// ProviderMessageReceived is the resolver for the providerMessageReceived field.
func (r *subscriptionResolver) ProviderMessageReceived(ctx context.Context, serviceProviderID string) (<-chan *model.Message, error) {
	panic(fmt.Errorf("not implemented: ProviderMessageReceived - providerMessageReceived"))
}

// ProviderWebhookDeliveryCompleted is the resolver for the providerWebhookDeliveryCompleted field.
func (r *subscriptionResolver) ProviderWebhookDeliveryCompleted(ctx context.Context, serviceProviderID string) (<-chan *model.WebhookDelivery, error) {
	panic(fmt.Errorf("not implemented: ProviderWebhookDeliveryCompleted - providerWebhookDeliveryCompleted"))
}

// ProviderBotActionExecuted is the resolver for the providerBotActionExecuted field.
func (r *subscriptionResolver) ProviderBotActionExecuted(ctx context.Context, serviceProviderID string) (<-chan *model.BotActionLog, error) {
	panic(fmt.Errorf("not implemented: ProviderBotActionExecuted - providerBotActionExecuted"))
}

// ProviderCampaignProgressUpdated is the resolver for the providerCampaignProgressUpdated field.
func (r *subscriptionResolver) ProviderCampaignProgressUpdated(ctx context.Context, serviceProviderID string) (<-chan *model.Campaign, error) {
	panic(fmt.Errorf("not implemented: ProviderCampaignProgressUpdated - providerCampaignProgressUpdated"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
