package events
package events

import (
	"context"
































































































































































































































































































}	}		}			}				c.client.XAck(ctx, c.stream, c.group, msg.ID)				}					continue					)						zap.Error(err),						zap.String("event_id", event.ID),					c.logger.Error("handler failed",				if err := handler(ctx, &event); err != nil {				}					continue					c.logger.Error("unmarshal stream event", zap.Error(err))				if err := json.Unmarshal([]byte(data), &event); err != nil {				var event Event				}					continue				if !ok {				data, ok := msg.Values["data"].(string)			for _, msg := range stream.Messages {		for _, stream := range streams {		}			continue			time.Sleep(time.Second)			c.logger.Error("stream read error", zap.Error(err))			}				continue			if err == redis.Nil {		if err != nil {		}).Result()			Block:    2 * time.Second,			Count:    c.batchSize,			Streams:  []string{c.stream, ">"},			Consumer: c.consumer,			Group:    c.group,		streams, err := c.client.XReadGroup(ctx, &redis.XReadGroupArgs{		}		default:			return		case <-ctx.Done():		select {	for {func (c *RedisStreamConsumer) consume(ctx context.Context, handler Handler) {}	return nil	go c.consume(ctx, handler)	}		return fmt.Errorf("create consumer group: %w", err)	if err != nil && !strings.Contains(err.Error(), "BUSYGROUP") {	err := c.client.XGroupCreateMkStream(ctx, c.stream, c.group, "0").Err()	// Create consumer group if it doesn't exist.func (c *RedisStreamConsumer) Start(ctx context.Context, handler Handler) error {// Start begins consuming events from the stream.}	}		batchSize: 10,		consumer:  consumer,		group:     group,		stream:    stream,		logger:    logger,		client:    client,	return &RedisStreamConsumer{func NewRedisStreamConsumer(client *redis.Client, logger *zap.Logger, stream, group, consumer string) *RedisStreamConsumer {// NewRedisStreamConsumer creates a consumer for Redis Streams with consumer group support.}	batchSize int64	consumer  string	group     string	stream    string	logger    *zap.Logger	client    *redis.Clienttype RedisStreamConsumer struct {// RedisStreamConsumer consumes events from a Redis Stream using consumer groups.}	return nilfunc (p *RedisStreamPublisher) Close() error {}	return err	_, err := pipe.Exec(ctx)	}		})			},				"data":       string(data),				"event_type": string(event.Type),			Values: map[string]interface{}{			Stream: p.streamName,		pipe.XAdd(ctx, &redis.XAddArgs{		}			return fmt.Errorf("marshal event %s: %w", event.ID, err)		if err != nil {		data, err := json.Marshal(event)	for _, event := range events {	pipe := p.client.Pipeline()func (p *RedisStreamPublisher) PublishBatch(ctx context.Context, events []*Event) error {}	return nil	)		zap.String("stream", p.streamName),		zap.String("event_id", event.ID),	p.logger.Debug("event published to stream",	}		return fmt.Errorf("publish to redis stream: %w", err)	if err != nil {	}).Result()		},			"data":       string(data),			"event_type": string(event.Type),		Values: map[string]interface{}{		Stream: p.streamName,	_, err = p.client.XAdd(ctx, &redis.XAddArgs{	}		return fmt.Errorf("marshal event: %w", err)	if err != nil {	data, err := json.Marshal(event)func (p *RedisStreamPublisher) Publish(ctx context.Context, event *Event) error {}	}		streamName: streamName,		logger:     logger,		client:     client,	return &RedisStreamPublisher{func NewRedisStreamPublisher(client *redis.Client, logger *zap.Logger, streamName string) *RedisStreamPublisher {// NewRedisStreamPublisher creates a publisher that uses Redis Streams for durability.}	streamName string	logger     *zap.Logger	client     *redis.Clienttype RedisStreamPublisher struct {// RedisStreamPublisher uses Redis Streams for durable event delivery.}	return nil	}		return s.pubsub.Close()	if s.pubsub != nil {func (s *RedisSubscriber) Close() error {}	}		}			}				)					zap.Error(err),					zap.String("event_type", string(event.Type)),					zap.String("event_id", event.ID),				s.logger.Error("event handler failed",			if err := handler(ctx, &event); err != nil {			}				continue				)					zap.String("channel", msg.Channel),					zap.Error(err),				s.logger.Error("failed to unmarshal event",			if err := json.Unmarshal([]byte(msg.Payload), &event); err != nil {			var event Event			}				return			if !ok {		case msg, ok := <-ch:			return		case <-ctx.Done():		select {	for {	ch := s.pubsub.Channel()func (s *RedisSubscriber) listen(ctx context.Context, handler Handler) {}	return nil	go s.listen(ctx, handler)	)		zap.String("channels", strings.Join(channels, ",")),	s.logger.Info("subscribed to events",	}		return fmt.Errorf("subscribe to redis channels: %w", err)	if err != nil {	_, err := s.pubsub.Receive(ctx)	// Wait for confirmation that subscription is created.	s.pubsub = s.client.Subscribe(ctx, channels...)	}		channels[i] = channelPrefix + string(et)	for i, et := range eventTypes {	channels := make([]string, len(eventTypes))func (s *RedisSubscriber) Subscribe(ctx context.Context, eventTypes []EventType, handler Handler) error {}	}		logger: logger,		client: client,	return &RedisSubscriber{func NewRedisSubscriber(client *redis.Client, logger *zap.Logger) *RedisSubscriber {// NewRedisSubscriber creates a new Redis-based event subscriber.}	pubsub *redis.PubSub	logger *zap.Logger	client *redis.Clienttype RedisSubscriber struct {// RedisSubscriber subscribes to events via Redis Pub/Sub.}	return nilfunc (p *RedisPublisher) Close() error {}	return nil	}		return fmt.Errorf("publish batch to redis: %w", err)	if err != nil {	_, err := pipe.Exec(ctx)	}		pipe.Publish(ctx, channel, data)		channel := channelPrefix + string(event.Type)		}			return fmt.Errorf("marshal event %s: %w", event.ID, err)		if err != nil {		data, err := json.Marshal(event)	for _, event := range events {	pipe := p.client.Pipeline()func (p *RedisPublisher) PublishBatch(ctx context.Context, events []*Event) error {}	return nil	)		zap.String("channel", channel),		zap.String("event_type", string(event.Type)),		zap.String("event_id", event.ID),	p.logger.Debug("event published",	}		return fmt.Errorf("publish event to redis: %w", err)	if err := p.client.Publish(ctx, channel, data).Err(); err != nil {	channel := channelPrefix + string(event.Type)	}		return fmt.Errorf("marshal event: %w", err)	if err != nil {	data, err := json.Marshal(event)func (p *RedisPublisher) Publish(ctx context.Context, event *Event) error {}	}		logger: logger,		client: client,	return &RedisPublisher{func NewRedisPublisher(client *redis.Client, logger *zap.Logger) *RedisPublisher {// NewRedisPublisher creates a new Redis-based event publisher.}	logger *zap.Logger	client *redis.Clienttype RedisPublisher struct {// RedisPublisher publishes events via Redis Pub/Sub.)	allChannel    = "trustinbox:events:*"	channelPrefix = "trustinbox:events:"const ()	"go.uber.org/zap"	"github.com/redis/go-redis/v9"	"time"	"strings"	"fmt"	"encoding/json"