package postgres
//go:build integration

package postgres_test

import (






























































































































































































































































}	}		t.Errorf("expected empty daily analytics, got %d", len(daily))	if len(daily) != 0 {	}		t.Fatalf("GetDailyAnalytics: %v", err)	if err != nil {	daily, err := repo.GetDailyAnalytics(ctx, spID, dateRange)	// Daily analytics with no rows	}		t.Errorf("expected 0 notifications for empty SP")	if stats.TotalNotificationsSent != 0 {	}		t.Fatalf("GetDashboardStats: %v", err)	if err != nil {	stats, err := repo.GetDashboardStats(ctx, spID)	// Dashboard stats for SP with no data	dateRange := entity.DateRange{Start: today, End: today}	today := time.Now().UTC().Truncate(24 * time.Hour)	ctx := context.Background()	repo := postgres.NewAnalyticsRepository(db)	t.Cleanup(func() { cleanAnalytics(t, db, spID) })	seedSP(t, db, spID)	spID := "20000000-0000-0000-0000-000000000099"	db := testDB(t)func TestAnalyticsRepo_EmptyResults(t *testing.T) {}	}		t.Errorf("ApprovalRate = %f, want ~0.8", cb.ApprovalRate)	if cb.ApprovalRate < 0.79 || cb.ApprovalRate > 0.81 {	}		t.Errorf("TotalApproved = %d, want 40", cb.TotalApproved)	if cb.TotalApproved != 40 {	}		t.Errorf("TotalRequested = %d, want 50", cb.TotalRequested)	if cb.TotalRequested != 50 {	}		t.Fatalf("GetCallbackAnalytics: %v", err)	if err != nil {	cb, err := repo.GetCallbackAnalytics(ctx, spID, dateRange)	dateRange := entity.DateRange{Start: today, End: today}	}		t.Fatalf("UpsertDailyMetrics: %v", err)	if err := repo.UpsertDailyMetrics(ctx, daily); err != nil {	}		CallbacksDenied:    10,		CallbacksApproved:  40,		CallbacksRequested: 50,		Date:              today,		ServiceProviderID: spID,		ID:                fmt.Sprintf("dc-%d", time.Now().UnixNano()),	daily := &entity.DailyAnalytics{	today := time.Now().UTC().Truncate(24 * time.Hour)	ctx := context.Background()	repo := postgres.NewAnalyticsRepository(db)	t.Cleanup(func() { cleanAnalytics(t, db, spID) })	seedSP(t, db, spID)	spID := "20000000-0000-0000-0000-000000000004"	db := testDB(t)func TestAnalyticsRepo_GetCallbackAnalytics(t *testing.T) {}	}		t.Errorf("DeliveryRate = %f, want ~0.9", notif.DeliveryRate)	if notif.DeliveryRate < 0.89 || notif.DeliveryRate > 0.91 {	}		t.Errorf("TotalDelivered = %d, want 180", notif.TotalDelivered)	if notif.TotalDelivered != 180 {	}		t.Errorf("TotalSent = %d, want 200", notif.TotalSent)	if notif.TotalSent != 200 {	}		t.Fatalf("GetNotificationAnalytics: %v", err)	if err != nil {	notif, err := repo.GetNotificationAnalytics(ctx, spID, dateRange)	dateRange := entity.DateRange{Start: today, End: today}	}		t.Fatalf("UpsertDailyMetrics: %v", err)	if err := repo.UpsertDailyMetrics(ctx, daily); err != nil {	}		NotificationsFailed:    20,		NotificationsDelivered: 180,		NotificationsSent:      200,		Date:                   today,		ServiceProviderID:      spID,		ID:                     fmt.Sprintf("dn-%d", time.Now().UnixNano()),	daily := &entity.DailyAnalytics{	today := time.Now().UTC().Truncate(24 * time.Hour)	ctx := context.Background()	repo := postgres.NewAnalyticsRepository(db)	t.Cleanup(func() { cleanAnalytics(t, db, spID) })	seedSP(t, db, spID)	spID := "20000000-0000-0000-0000-000000000003"	db := testDB(t)func TestAnalyticsRepo_GetNotificationAnalytics(t *testing.T) {}	}		t.Fatalf("GetDailyAnalytics len = %d, want 2", len(results))	if len(results) != 2 {	}		t.Fatalf("GetDailyAnalytics: %v", err)	if err != nil {	results, err := repo.GetDailyAnalytics(ctx, spID, dateRange)	dateRange := entity.DateRange{Start: yesterday, End: today}	}		}			t.Fatalf("UpsertDailyMetrics %d: %v", i, err)		if err := repo.UpsertDailyMetrics(ctx, daily); err != nil {		}			NotificationsFailed:    (i + 1) * 2,			NotificationsDelivered: (i + 1) * 8,			NotificationsSent:      (i + 1) * 10,			Date:                   date,			ServiceProviderID:      spID,			ID:                     fmt.Sprintf("dd-%d-%d", time.Now().UnixNano(), i),		daily := &entity.DailyAnalytics{	for i, date := range []time.Time{yesterday, today} {	yesterday := today.AddDate(0, 0, -1)	today := time.Now().UTC().Truncate(24 * time.Hour)	ctx := context.Background()	repo := postgres.NewAnalyticsRepository(db)	t.Cleanup(func() { cleanAnalytics(t, db, spID) })	seedSP(t, db, spID)	spID := "20000000-0000-0000-0000-000000000002"	db := testDB(t)func TestAnalyticsRepo_GetDailyAnalytics(t *testing.T) {}	}		t.Errorf("TotalNotificationsSent after upsert = %d, want >= 150", stats.TotalNotificationsSent)	if stats.TotalNotificationsSent < 150 {	}		t.Fatalf("GetDashboardStats 2: %v", err)	if err != nil {	stats, err = repo.GetDashboardStats(ctx, spID)	}		t.Fatalf("UpsertDailyMetrics 2: %v", err)	if err := repo.UpsertDailyMetrics(ctx, &daily2); err != nil {	daily2.NotificationsDelivered = 45	daily2.NotificationsSent = 50	daily2.ID = fmt.Sprintf("ad2-%d", time.Now().UnixNano())	daily2 := *daily	// Upsert again (should add to existing row)	}		t.Errorf("NotificationsDelivered = %d, want >= 90", stats.NotificationsDelivered)	if stats.NotificationsDelivered < 90 {	}		t.Errorf("TotalNotificationsSent = %d, want >= 100", stats.TotalNotificationsSent)	if stats.TotalNotificationsSent < 100 {	}		t.Fatalf("GetDashboardStats: %v", err)	if err != nil {	stats, err := repo.GetDashboardStats(ctx, spID)	// GetDashboardStats	}		t.Fatalf("UpsertDailyMetrics: %v", err)	if err := repo.UpsertDailyMetrics(ctx, daily); err != nil {	// Upsert	}		AvgResponseTimeMS:      0,		ChurnedCustomers:       1,		NewCustomers:           10,		WebhooksFailed:         2,		WebhooksSent:           40,		BotEscalations:         5,		BotActions:             30,		CampaignsDelivered:     200,		CampaignsSent:          2,		PolicyApprovals:        50,		PolicyDenials:          3,		CallbacksDenied:        5,		CallbacksApproved:      15,		CallbacksRequested:     20,		NotificationsFailed:    10,		NotificationsDelivered: 90,		NotificationsSent:      100,		Date:                   today,		ServiceProviderID:      spID,		ID:                     fmt.Sprintf("ad-%d", time.Now().UnixNano()),	daily := &entity.DailyAnalytics{	today := time.Now().UTC().Truncate(24 * time.Hour)	ctx := context.Background()	repo := postgres.NewAnalyticsRepository(db)	t.Cleanup(func() { cleanAnalytics(t, db, spID) })	seedSP(t, db, spID)	spID := "20000000-0000-0000-0000-000000000001"	db := testDB(t)func TestAnalyticsRepo_UpsertAndGetDashboard(t *testing.T) {}	db.Exec(`DELETE FROM analytics_daily WHERE service_provider_id = $1`, spID)	t.Helper()func cleanAnalytics(t *testing.T, db *sql.DB, spID string) {}	}		t.Fatalf("seed sp: %v", err)	if err != nil {	)		 ON CONFLICT (id) DO NOTHING`, spID,		 VALUES ($1, 'Test SP', 'ACTIVE', NOW(), NOW())		`INSERT INTO service_providers (id, name, status, created_at, updated_at)	_, err := db.Exec(	t.Helper()func seedSP(t *testing.T, db *sql.DB, spID string) {}	return db	t.Cleanup(func() { db.Close() })	}		t.Skipf("database not available: %v", err)	if err := db.Ping(); err != nil {	}		t.Fatalf("open db: %v", err)	if err != nil {	db, err := sql.Open("postgres", dsn)	}		dsn = "postgres://trustinbox:trustinbox@localhost:5432/trustinbox_test?sslmode=disable"	if dsn == "" {	dsn := os.Getenv("TEST_DATABASE_URL")	t.Helper()func testDB(t *testing.T) *sql.DB {)	"github.com/trustinbox/analytics-service/internal/infra/postgres"	"github.com/trustinbox/analytics-service/internal/domain/entity"	_ "github.com/lib/pq"	"time"	"testing"	"os"	"fmt"	"database/sql"	"context"